# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from oca.models.base_model_ import Model
from oca import util


class HomeScreenContentType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NATIVE = "native"
    EMBEDDED_APP = "embedded_app"
    def __init__(self):  # noqa: E501
        """HomeScreenContentType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'HomeScreenContentType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HomeScreenContentType of this HomeScreenContentType.  # noqa: E501
        :rtype: HomeScreenContentType
        """
        return util.deserialize_model(dikt, cls)
