# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from oca.models.base_model_ import Model
from oca.models.home_screen_bottom_navigation import HomeScreenBottomNavigation
from oca.models.home_screen_bottom_sheet import HomeScreenBottomSheet
from oca.models.home_screen_content import HomeScreenContent
from oca import util

from oca.models.home_screen_bottom_navigation import HomeScreenBottomNavigation  # noqa: E501
from oca.models.home_screen_bottom_sheet import HomeScreenBottomSheet  # noqa: E501
from oca.models.home_screen_content import HomeScreenContent  # noqa: E501

class HomeScreen(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, version=None, content=None, bottom_navigation=None, bottom_sheet=None, default_language=None, translations=None):  # noqa: E501
        """HomeScreen - a model defined in OpenAPI

        :param version: The version of this HomeScreen.  # noqa: E501
        :type version: int
        :param content: The content of this HomeScreen.  # noqa: E501
        :type content: HomeScreenContent
        :param bottom_navigation: The bottom_navigation of this HomeScreen.  # noqa: E501
        :type bottom_navigation: HomeScreenBottomNavigation
        :param bottom_sheet: The bottom_sheet of this HomeScreen.  # noqa: E501
        :type bottom_sheet: HomeScreenBottomSheet
        :param default_language: The default_language of this HomeScreen.  # noqa: E501
        :type default_language: str
        :param translations: The translations of this HomeScreen.  # noqa: E501
        :type translations: Dict[str, Dict[str, str]]
        """
        self.openapi_types = {
            'version': int,
            'content': HomeScreenContent,
            'bottom_navigation': HomeScreenBottomNavigation,
            'bottom_sheet': HomeScreenBottomSheet,
            'default_language': str,
            'translations': Dict[str, Dict[str, str]]
        }

        self.attribute_map = {
            'version': 'version',
            'content': 'content',
            'bottom_navigation': 'bottom_navigation',
            'bottom_sheet': 'bottom_sheet',
            'default_language': 'default_language',
            'translations': 'translations'
        }

        self._version = version
        self._content = content
        self._bottom_navigation = bottom_navigation
        self._bottom_sheet = bottom_sheet
        self._default_language = default_language
        self._translations = translations

    @classmethod
    def from_dict(cls, dikt) -> 'HomeScreen':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HomeScreen of this HomeScreen.  # noqa: E501
        :rtype: HomeScreen
        """
        return util.deserialize_model(dikt, cls)

    @property
    def version(self):
        """Gets the version of this HomeScreen.


        :return: The version of this HomeScreen.
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this HomeScreen.


        :param version: The version of this HomeScreen.
        :type version: int
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    @property
    def content(self):
        """Gets the content of this HomeScreen.


        :return: The content of this HomeScreen.
        :rtype: HomeScreenContent
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this HomeScreen.


        :param content: The content of this HomeScreen.
        :type content: HomeScreenContent
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")  # noqa: E501

        self._content = content

    @property
    def bottom_navigation(self):
        """Gets the bottom_navigation of this HomeScreen.


        :return: The bottom_navigation of this HomeScreen.
        :rtype: HomeScreenBottomNavigation
        """
        return self._bottom_navigation

    @bottom_navigation.setter
    def bottom_navigation(self, bottom_navigation):
        """Sets the bottom_navigation of this HomeScreen.


        :param bottom_navigation: The bottom_navigation of this HomeScreen.
        :type bottom_navigation: HomeScreenBottomNavigation
        """
        if bottom_navigation is None:
            raise ValueError("Invalid value for `bottom_navigation`, must not be `None`")  # noqa: E501

        self._bottom_navigation = bottom_navigation

    @property
    def bottom_sheet(self):
        """Gets the bottom_sheet of this HomeScreen.


        :return: The bottom_sheet of this HomeScreen.
        :rtype: HomeScreenBottomSheet
        """
        return self._bottom_sheet

    @bottom_sheet.setter
    def bottom_sheet(self, bottom_sheet):
        """Sets the bottom_sheet of this HomeScreen.


        :param bottom_sheet: The bottom_sheet of this HomeScreen.
        :type bottom_sheet: HomeScreenBottomSheet
        """
        if bottom_sheet is None:
            raise ValueError("Invalid value for `bottom_sheet`, must not be `None`")  # noqa: E501

        self._bottom_sheet = bottom_sheet

    @property
    def default_language(self):
        """Gets the default_language of this HomeScreen.

        Language to use when the user his language is not one of the available ones in the translation mapping  # noqa: E501

        :return: The default_language of this HomeScreen.
        :rtype: str
        """
        return self._default_language

    @default_language.setter
    def default_language(self, default_language):
        """Sets the default_language of this HomeScreen.

        Language to use when the user his language is not one of the available ones in the translation mapping  # noqa: E501

        :param default_language: The default_language of this HomeScreen.
        :type default_language: str
        """
        if default_language is None:
            raise ValueError("Invalid value for `default_language`, must not be `None`")  # noqa: E501

        self._default_language = default_language

    @property
    def translations(self):
        """Gets the translations of this HomeScreen.

        Translations for any string which could be translated on the homescreen. Properties that should be translated should contain a $ prefix. For example, label -> $trash_calendar  # noqa: E501

        :return: The translations of this HomeScreen.
        :rtype: Dict[str, Dict[str, str]]
        """
        return self._translations

    @translations.setter
    def translations(self, translations):
        """Sets the translations of this HomeScreen.

        Translations for any string which could be translated on the homescreen. Properties that should be translated should contain a $ prefix. For example, label -> $trash_calendar  # noqa: E501

        :param translations: The translations of this HomeScreen.
        :type translations: Dict[str, Dict[str, str]]
        """
        if translations is None:
            raise ValueError("Invalid value for `translations`, must not be `None`")  # noqa: E501

        self._translations = translations
