# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from oca.models.base_model_ import Model
from oca import util


class HomeScreenContent(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, embedded_app=None, service_email=None):  # noqa: E501
        """HomeScreenContent - a model defined in OpenAPI

        :param type: The type of this HomeScreenContent.  # noqa: E501
        :type type: str
        :param embedded_app: The embedded_app of this HomeScreenContent.  # noqa: E501
        :type embedded_app: str
        :param service_email: The service_email of this HomeScreenContent.  # noqa: E501
        :type service_email: str
        """
        self.openapi_types = {
            'type': str,
            'embedded_app': str,
            'service_email': str
        }

        self.attribute_map = {
            'type': 'type',
            'embedded_app': 'embedded_app',
            'service_email': 'service_email'
        }

        self._type = type
        self._embedded_app = embedded_app
        self._service_email = service_email

    @classmethod
    def from_dict(cls, dikt) -> 'HomeScreenContent':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HomeScreenContent of this HomeScreenContent.  # noqa: E501
        :rtype: HomeScreenContent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self):
        """Gets the type of this HomeScreenContent.


        :return: The type of this HomeScreenContent.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this HomeScreenContent.


        :param type: The type of this HomeScreenContent.
        :type type: str
        """
        allowed_values = ["native", "embedded_app"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def embedded_app(self):
        """Gets the embedded_app of this HomeScreenContent.

        Only set when 'type' is embedded_app  # noqa: E501

        :return: The embedded_app of this HomeScreenContent.
        :rtype: str
        """
        return self._embedded_app

    @embedded_app.setter
    def embedded_app(self, embedded_app):
        """Sets the embedded_app of this HomeScreenContent.

        Only set when 'type' is embedded_app  # noqa: E501

        :param embedded_app: The embedded_app of this HomeScreenContent.
        :type embedded_app: str
        """

        self._embedded_app = embedded_app

    @property
    def service_email(self):
        """Gets the service_email of this HomeScreenContent.

        This service will be used as 'context' in the embedded app, to set user data / service data.  # noqa: E501

        :return: The service_email of this HomeScreenContent.
        :rtype: str
        """
        return self._service_email

    @service_email.setter
    def service_email(self, service_email):
        """Sets the service_email of this HomeScreenContent.

        This service will be used as 'context' in the embedded app, to set user data / service data.  # noqa: E501

        :param service_email: The service_email of this HomeScreenContent.
        :type service_email: str
        """

        self._service_email = service_email
