# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from oca.models.base_model_ import Model
from oca import util


class HomeScreenNavigationButton(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, icon=None, label=None, action=None):  # noqa: E501
        """HomeScreenNavigationButton - a model defined in OpenAPI

        :param icon: The icon of this HomeScreenNavigationButton.  # noqa: E501
        :type icon: str
        :param label: The label of this HomeScreenNavigationButton.  # noqa: E501
        :type label: str
        :param action: The action of this HomeScreenNavigationButton.  # noqa: E501
        :type action: str
        """
        self.openapi_types = {
            'icon': str,
            'label': str,
            'action': str
        }

        self.attribute_map = {
            'icon': 'icon',
            'label': 'label',
            'action': 'action'
        }

        self._icon = icon
        self._label = label
        self._action = action

    @classmethod
    def from_dict(cls, dikt) -> 'HomeScreenNavigationButton':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HomeScreenNavigationButton of this HomeScreenNavigationButton.  # noqa: E501
        :rtype: HomeScreenNavigationButton
        """
        return util.deserialize_model(dikt, cls)

    @property
    def icon(self):
        """Gets the icon of this HomeScreenNavigationButton.


        :return: The icon of this HomeScreenNavigationButton.
        :rtype: str
        """
        return self._icon

    @icon.setter
    def icon(self, icon):
        """Sets the icon of this HomeScreenNavigationButton.


        :param icon: The icon of this HomeScreenNavigationButton.
        :type icon: str
        """
        if icon is None:
            raise ValueError("Invalid value for `icon`, must not be `None`")  # noqa: E501

        self._icon = icon

    @property
    def label(self):
        """Gets the label of this HomeScreenNavigationButton.


        :return: The label of this HomeScreenNavigationButton.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this HomeScreenNavigationButton.


        :param label: The label of this HomeScreenNavigationButton.
        :type label: str
        """
        if label is None:
            raise ValueError("Invalid value for `label`, must not be `None`")  # noqa: E501

        self._label = label

    @property
    def action(self):
        """Gets the action of this HomeScreenNavigationButton.


        :return: The action of this HomeScreenNavigationButton.
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this HomeScreenNavigationButton.


        :param action: The action of this HomeScreenNavigationButton.
        :type action: str
        """
        if action is None:
            raise ValueError("Invalid value for `action`, must not be `None`")  # noqa: E501

        self._action = action
