# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from oca.models.base_model_ import Model
from oca.models.homescreen_navigation_button import HomescreenNavigationButton
from oca import util

from oca.models.homescreen_navigation_button import HomescreenNavigationButton  # noqa: E501

class HomescreenBottomNavigation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, buttons=None):  # noqa: E501
        """HomescreenBottomNavigation - a model defined in OpenAPI

        :param buttons: The buttons of this HomescreenBottomNavigation.  # noqa: E501
        :type buttons: List[HomescreenNavigationButton]
        """
        self.openapi_types = {
            'buttons': List[HomescreenNavigationButton]
        }

        self.attribute_map = {
            'buttons': 'buttons'
        }

        self._buttons = buttons

    @classmethod
    def from_dict(cls, dikt) -> 'HomescreenBottomNavigation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HomescreenBottomNavigation of this HomescreenBottomNavigation.  # noqa: E501
        :rtype: HomescreenBottomNavigation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def buttons(self):
        """Gets the buttons of this HomescreenBottomNavigation.


        :return: The buttons of this HomescreenBottomNavigation.
        :rtype: List[HomescreenNavigationButton]
        """
        return self._buttons

    @buttons.setter
    def buttons(self, buttons):
        """Sets the buttons of this HomescreenBottomNavigation.


        :param buttons: The buttons of this HomescreenBottomNavigation.
        :type buttons: List[HomescreenNavigationButton]
        """

        self._buttons = buttons
