// tslint:disable
/**
 * Our City App
 * Our City App internal apis
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Content of the homescreen, native or an embedded app
 * @export
 * @interface HomeScreenContent
 */
export interface HomeScreenContent {
    /**
     * @type {string}
     * @memberof HomeScreenContent
     */
    type: HomeScreenContentTypeEnum;
    /**
     * Only set when \'type\' is embedded_app
     * @type {string}
     * @memberof HomeScreenContent
     */
    embedded_app?: string;
    /**
     * Content of the home screen
     * @type {Array<{ [key: string]: object; }>}
     * @memberof HomeScreenContent
     */
    sections?: Array<{ [key: string]: object; }>;
    /**
     * This service will be used as \'context\' in the embedded app, to set user data / service data.
     * @type {string}
     * @memberof HomeScreenContent
     */
    service_email?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum HomeScreenContentTypeEnum {
    Native = 'native',
    EmbeddedApp = 'embedded_app'
}

