// tslint:disable
/**
 * Our City App
 * Our City App internal apis
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface HomeScreenBottomSheetHeader
 */
export interface HomeScreenBottomSheetHeader {
    /**
     * @type {string}
     * @memberof HomeScreenBottomSheetHeader
     */
    title: string;
    /**
     * @type {string}
     * @memberof HomeScreenBottomSheetHeader
     */
    subtitle?: string | null;
    /**
     * @type {string}
     * @memberof HomeScreenBottomSheetHeader
     */
    image?: string | null;
}
