# -*- coding: utf-8 -*-
# COPYRIGHT (C) 2011-2014 MOBICAGE NV
# ALL RIGHTS RESERVED.
#
# ALTHOUGH YOU MAY BE ABLE TO READ THE CONTENT OF THIS FILE, THIS FILE
# CONTAINS CONFIDENTIAL INFORMATION OF MOBICAGE NV. YOU ARE NOT ALLOWED
# TO MODIFY, REPRODUCE, DISCLOSE, PUBLISH OR DISTRIBUTE ITS CONTENT,
# EMBED IT IN OTHER SOFTWARE, OR CREATE DERIVATIVE WORKS, UNLESS PRIOR
# WRITTEN PERMISSION IS OBTAINED FROM MOBICAGE NV.
#
# THE COPYRIGHT NOTICE ABOVE DOES NOT EVIDENCE ANY ACTUAL OR INTENDED
# PUBLICATION OF SUCH SOURCE CODE.
#
# @@license_version:1.7@@

SECRET_PP = "zxdlkujvhbdflsjzghuvadourgvbldhjkrfvosgadruyfgbaer;kiufhoaeyrgbdflscgaeortgh;w"
SECRET_AP = ";dfiuzhfq3p4[98hrf097yew4q;ctuhertw so87eqr;bgq3p98023r;vbnp[f908CQ3]4MR1§90    ]WIUAE9R8HGJKW45UGH0QE78YTHOU45H908YEQ[OUIH3Q4087TYGQ"