# coding: utf-8

"""
    Our City App

    Our City App internal apis  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from oca.configuration import Configuration


class HomescreenBottomSheet(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'header': 'HomescreenBottomSheetHeader',
        'rows': 'list[dict(str, object)]'
    }

    attribute_map = {
        'header': 'header',
        'rows': 'rows'
    }

    def __init__(self, header=None, rows=None, local_vars_configuration=None):  # noqa: E501
        """HomescreenBottomSheet - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._header = None
        self._rows = None
        self.discriminator = None

        self.header = header
        self.rows = rows

    @property
    def header(self):
        """Gets the header of this HomescreenBottomSheet.  # noqa: E501


        :return: The header of this HomescreenBottomSheet.  # noqa: E501
        :rtype: HomescreenBottomSheetHeader
        """
        return self._header

    @header.setter
    def header(self, header):
        """Sets the header of this HomescreenBottomSheet.


        :param header: The header of this HomescreenBottomSheet.  # noqa: E501
        :type: HomescreenBottomSheetHeader
        """
        if self.local_vars_configuration.client_side_validation and header is None:  # noqa: E501
            raise ValueError("Invalid value for `header`, must not be `None`")  # noqa: E501

        self._header = header

    @property
    def rows(self):
        """Gets the rows of this HomescreenBottomSheet.  # noqa: E501


        :return: The rows of this HomescreenBottomSheet.  # noqa: E501
        :rtype: list[dict(str, object)]
        """
        return self._rows

    @rows.setter
    def rows(self, rows):
        """Sets the rows of this HomescreenBottomSheet.


        :param rows: The rows of this HomescreenBottomSheet.  # noqa: E501
        :type: list[dict(str, object)]
        """
        if self.local_vars_configuration.client_side_validation and rows is None:  # noqa: E501
            raise ValueError("Invalid value for `rows`, must not be `None`")  # noqa: E501

        self._rows = rows

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HomescreenBottomSheet):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HomescreenBottomSheet):
            return True

        return self.to_dict() != other.to_dict()
