runtime: python27
service: service-workers
api_version: 1
threadsafe: true
instance_class: F1

inbound_services:
  - warmup

skip_files:
  - '^(.*/)?#.*#$'
  - ^(.*/)?.*~$
  - '^(.*/)?.*\.py[co]$'
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - lib/PIL*
  - lib/lxml*
  - lib/Crypto*

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1

handlers:
  - url: /_ah/queue/deferred
    script: main.app
    login: admin
  - url: /cron/.*
    script: main.app
    login: admin
    secure: always
  - url: /.*
    script: main.app
    secure: always
