#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2017 GIG Technology NV
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# @@license_version:1.3@@

# Generated by Mobitrans at Wed Jan 13 10:50:42 2016

translations = \
{u'en': {u'jukebox-configuration': u'Jukebox',
         u'jukebox-disabled': u'Jukebox Disabled',
         u'jukebox-enabled': u'Jukebox Enabled',
         u'jukebox-off-button': u'OFF',
         u'jukebox-on-button': u'ON',
         u'settings-qr-connect': u'DJ-Matic app',
         u'title': u'DJ-Matic'},
 u'es': {u'jukebox-configuration': u'Jukebox',
         u'jukebox-disabled': u'Jukebox Deshabilitado',
         u'jukebox-enabled': u'Jukebox Habilitado',
         u'jukebox-off-button': u'Apagar',
         u'jukebox-on-button': u'Encender',
         u'title': u'DJ-Matic'},
 u'fr': {u'jukebox-configuration': u'Jukebox',
         u'jukebox-disabled': u'Jukebox D\xe9sactiv\xe9',
         u'jukebox-enabled': u'Jukebox Activ\xe9',
         u'jukebox-off-button': u'OFF',
         u'jukebox-on-button': u'ON',
         u'title': u'DJ-Matic'},
 u'nl': {u'jukebox-configuration': u'Jukebox',
         u'jukebox-disabled': u'Jukebox is uitgeschakeld',
         u'jukebox-enabled': u'Jukebox is ingeschakeld',
         u'jukebox-off-button': u'UIT',
         u'jukebox-on-button': u'AAN',
         u'settings-qr-connect': u'DJ-Matic app',
         u'title': u'DJ-Matic'},
 u'ro': {u'jukebox-configuration': u'Tonomat',
         u'jukebox-disabled': u'Tonomat dezactivat',
         u'jukebox-enabled': u'Tonamat activat',
         u'jukebox-off-button': u'Oprit',
         u'jukebox-on-button': u'Pornit',
         u'settings-qr-connect': u'DJ-Matic app',
         u'title': u'DJ-Matic'}}
