runtime: python27
api_version: 1

threadsafe: true
instance_class: F2
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 2
  max_concurrent_requests: 20
  max_pending_latency: 500ms
  min_pending_latency: 250ms

handlers:
- url: /internal/.*
  script: main_google_authenticated.app
  login: required
  secure: always

- url: /admin/.*
  script: main_admin.app
  login: admin
  secure: always

- url: /ourcityapp
  script: main_unauthenticated.app
  secure: always

- url: /(common|flex)/
  script: main_unauthenticated.app
  secure: always

- url: /(common|flex)/.*
  script: main_authenticated.app
  secure: always

- url: /solutions/common/public/.*
  script: main_unauthenticated.app
  secure: always

- url: /bob/.*
  script: main_unauthenticated.app
  secure: always

- url: /shop/(products|invoices)/export
  script: main_unauthenticated.app
  secure: always

- url: /shop/prospects/callback
  script: main_unauthenticated.app
  secure: always

- url: /shop/prospects/discover/callback
  script: main_unauthenticated.app
  secure: always

- url: /shop/oauth2callback
  script: main_google_authenticated.app
  secure: always

- url: /customers/.*
  script: main_unauthenticated.app
  secure: always

- url: /vcards/?.*
  script: main_unauthenticated.app
  secure: always

- url: /unauthenticated/loyalty/.*
  script: main_unauthenticated.app
  secure: always

- url: /unauthenticated/osa/.*
  script: main_unauthenticated.app
  secure: always
  
- url: /unauthenticated/payments/.*
  script: main_unauthenticated.app
  secure: always  

- url: /version
  script: main_unauthenticated.app
  secure: always

- url: /terms
  script: main_authenticated.app
  secure: always

admin_console:
  pages:
  - name: OSA Launcher
    url: /admin/osa/launcher/apps
