#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2020 Green Valley Belgium NV
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# @@license_version:1.7@@

# WARNING: this is a generated file - DO NOT MODIFY

import logging

__all__ = [ 'localize', 'SUPPORTED_LANGUAGES' ]

DEFAULT_LANGUAGE = "en"

def localize(lang, key, language_fallback=True, **kwargs):
    if not lang:
        lang = DEFAULT_LANGUAGE
    lang = lang.replace('-', '_')
    if lang not in D:
        if '_' in lang:
            lang = lang.split('_')[0]
            if lang not in D:
                if not language_fallback:
                    return None
                lang = DEFAULT_LANGUAGE
        elif language_fallback:
            lang = DEFAULT_LANGUAGE
        else:
            return None
    langdict = D[lang]
    if key not in langdict:
        if not language_fallback:
            return None
        # Fall back to default language
        if lang != DEFAULT_LANGUAGE:
            logging.warn("Translation key %s not found in language %s - fallback to default" % (key, lang))
            lang = DEFAULT_LANGUAGE
            langdict = D[lang]
    if key in langdict:
        return langdict[key] % kwargs
    logging.warn("Translation key %s not found in default language. Fallback to key" % key)
    return unicode(key) % kwargs

D = { }

# Generated by Mobitrans at Tue Sep 17 08:22:52 2019


# ###########################################################################################

D["en"] = {
"""starting_this_week""": u"""Starting this week""",
"""app_jobs_title""": u"""Welcome to JOBS!""",
"""app_jobs_description""": u"""Looking for a new job challenge? From now on you will find all vacancies of local entrepreneurs, starting with those from your direct environment. Simply swipe through our local & regional job offers, supplemented with all vacancies from all over Flanders via the integration with VDAB. Set your preferences & get started. - Good luck!""",
"""at_least_one_job_domain_required""": u"""At least one job domain is required""",
"""job_info_text""": u"""Let your potential future employer know why you're interrested in this job. They will receive your name, email address and avatar unless you turn on 'anonymous'.""",
"""at_least_one_contract_type_required""": u"""At least one contract type is required""",
"""open_chat""": u"""Open chat...""",
"""saved""": u"""Saved""",
"""save""": u"""Save""",
"""update_app_to_use_feat""": u"""You need to update the app to use this feature.""",
"""gipod_notification_msg""": u"""From now on you will receive a message every Sunday with hindrance in your neighborhood.""",
"""gipod_notification_disabled_msg""": u"""You will no longer receive a message on Sunday with hindrance in your neighborhood.""",
"""hindrance_around_you""": u"""Hindrance around you""",
"""no_hindrance_at_location""": u"""#### No hindrance.\n\nThere's no hindrance at this location. Zoom out on the the map to see more.""",
"""next_x_days""": u"""Next %(days)s days""",
"""all""": u"""All""",
"""Reported""": u"""Reported""",
"""In Progress""": u"""In Progress""",
"""Resolved""": u"""Resolved""",
"""Call""": u"""Call""",
"""Directions""": u"""Directions""",
"""Saved""": u"""Saved""",

"""reports_around_you""": u"""Reports around you""",
"""no_reports_at_location""": u"""#### No reports.\n\nThere are no reports at this location. Zoom out on the the map to see more.""",

"""services_around_you""": u"""Services around you""",
"""no_services_at_location""": u"""#### No services.\n\nThere are no services at this location. Zoom out on the the map to see more.""",

"""open""": u"""Open""",
"""closed""": u"""Closed""",
"""always_closed""": u"""Always closed""",
"""open_24_hours""": u"""Open 24 hours""",
"""open_until""": u"""Open until %(time)s""",
"""opens_on_time""": u"""Opens at %(time)s""",
"""opens_on_day_and_time""": u"""Opens on %(day)s at %(time)s""",

"""New location updates""": u"""New location updates""",
"""%(name)s this week there are %(count)s new works, festivities or events planned around you""": u"""%(name)s this week there are %(count)s new works, festivities or events planned around you""",

"""%(app_name)s has %(count)d new messages for you""": u"""%(app_name)s has %(count)d new messages for you""",


"""%(app_name)s has 1 new message for you""": u"""%(app_name)s has 1 new message for you""",


"""%(app_name)s mobile registration""": u"""%(app_name)s mobile registration""",


"""%(count)s new matches""": u"""%(count)s new matches""",


"""%(name)s accepted your location sharing request.
Latest information:

Accuracy: %(accuracy)sm""": u"""%(name)s accepted your location sharing request.
Latest information:

Accuracy: %(accuracy)sm""",


"""%(name)s accepted your location sharing request. Unfortunately we could not determine his/her location at this moment.""": u"""%(name)s accepted your location sharing request. Unfortunately we could not determine his/her location at this moment.""",


"""%(name)s added a personal note:
%(message)s""": u"""%(name)s added a personal note:
%(message)s""",


"""%(name)s declined your request to track his/her location.""": u"""%(name)s declined your request to track his/her location.""",


"""%(name)s does not have a device which supports location tracking.""": u"""%(name)s does not have a device which supports location tracking.""",


"""%(name)s invites you to the %(app_name)s app!""": u"""%(name)s invites you to the %(app_name)s app!""",


"""%(name)s just joined %(app_name)s, and we found you in his facebook friends list!""": u"""%(name)s just joined %(app_name)s, and we found you in his/her Facebook friends list.""",


"""%(name_or_email)s added a personal note:

%(message)s""": u"""%(name_or_email)s added a personal note:

%(message)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.

About %(service_name)s:
%(service_description)s""": u"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.

About %(service_name)s:
%(service_description)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.""": u"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.""",


"""_automatic_detection_invitation""": u"""Hello,

We just welcomed you in our company.
Did you know we also offer our services through the %(app_name)s app?
Click the \"Add to this app\" button to add us to your services list.

Kind regards,
%(service_name)s.""",


"""_enable_location_services_ios7""": u"""To turn on location services:
1. Leave the %(app_name)s app and go to the Settings app
2. Tap Privacy > Location Services
3. Search for %(app_name)s and toggle the switch to ON""",


"""_enable_location_services_ios8""": u"""To turn on location services:
1. Leave the %(app_name)s app and go to the Settings app
2. Tap Privacy > Location Services
3. Search for %(app_name)s, tap on %(app_name)s and set location access to 'Always'""",


"""_friend_denied_location_services""": u"""%(name)s has disabled location services for the %(app_name)s app""",


"""_friendship_accepted""": u"""Hello %(name)s,
%(friend_name)s is now connected to you.""",


"""_friendship_established""": u"""Hello %(name)s,
You are now friends with %(friend_name)s.""",


"""_friendship_request_failed""": u"""Hi %(name)s,
Your connection request with %(friend_name)s failed.
Press the invite button to invite %(friend_name)s.""",


"""_invited_too_often""": u"""Hello %(name)s,
You invited %(friend_email)s 3 times.
To prevent spam, %(app_name)s will not send any more invitations.""",


"""_invited_too_often_this_week""": u"""Hello %(name)s,
You already invited %(friend_email)s earlier this week.
To prevent spam, %(app_name)s will not send any more invitations.""",


"""_invited_yourself""": u"""Hello %(name)s,
You tried to become friends with yourself.
Unfortunately this is not possible.""",


"""_invitee_was_already_friend""": u"""Hello %(name)s,
You tried to invite %(friend_email)s who is already in your friend list.""",


"""_location_services_denied""": u"""%(name)s requested your location, but you have disabled location services for the %(app_name)s app.""",


"""_unsupported_attachment_file_type""": u"""Unsupported file type for attachment %(url)s
We only support pdf, jpeg and png files""",


"""_welcome_message""": u"""Welcome to the %(app_name)s app!

Connect to your favorite suppliers, associations, care institutions and friends and start communicating.

Happy messaging!

Request your own application as a local business, association or health care provider by using the button below or contact us at %(contact_email_address)s""",


"""A-Z""": u"""A-Z""",


"""About""": u"""About""",


"""Accept invitation""": u"""Accept invitation""",


"""account_already_deactivated""": u"""You are not subscribed (anymore) to the %(app_name)s app with this account (%(account)s).""",


"""account_already_disconnected_from_service""": u"""You are not subscribed (anymore) to %(service_name)s.""",


"""Add to my services""": u"""Add to my services""",


"""Address""": u"""Address""",


"""All the news of our app""": u"""All the news of our app""",


"""An unknown error has occurred""": u"""An unknown error has occurred""",


"""anonymous_user""": u"""Anonymous user""",


"""answer""": u"""Answer""",


"""App news""": u"""App news""",


"""app""": u"""App""",


"""app_website_oca""": u"""http://ourcityapps.com""",


"""app_website_rogerthat""": u"""https://rogerth.at""",


"""around_you""": u"""Around you""",


"""association""": u"""Association""",


"""Associations""": u"""Associations""",


"""broadcast_reminder_explanation""": u"""You receive this notification because you are subscribed to: %(broadcast_type)s""",


"""button""": u"""Button""",


"""Can not connect to server""": u"""Can not connect to server""",


"""Cancel""": u"""Cancel""",


"""cannot_register_app_disabled""": u"""Sorry, you cannot complete the registration because the %(app)s app is no longer available.""",


"""Care""": u"""Care""",


"""chat_error_delete_last_admin""": u"""The last admin of a chat cannot be removed""",


"""City news""": u"""City news""",


"""click_here_to_reset_your_app_password""": u"""Click here to reset your %(app_name)s password.""",


"""Community news""": u"""Community news""",


"""Coronavirus info""": u"""Coronavirus info""",


"""The latest information about COVID-19""": u"""The latest information about COVID-19""",


"""Community Services""": u"""Community Services""",


"""community_service""": u"""Community service""",


"""continue""": u"""Continue""",


"""Could not determine file type for attachment %(url)s""": u"""Could not determine file type for attachment %(url)s""",


"""Could not download attachment %(url)s""": u"""Could not download attachment %(url)s""",


"""Current polls""": u"""Current polls""",


"""current-version""": u"""Current version""",


"""date""": u"""Date""",


"""Deactivate""": u"""Deactivate""",


"""dear_name""": u"""Dear %(name)s""",


"""Decline invitation""": u"""Decline invitation""",


"""Discover our new app""": u"""Discover our app""",


"""Distance: %(distance)s km""": u"""Distance: %(distance)s km""",


"""E-mail address""": u"""E-mail address""",


"""eID data""": u"""eID data""",


"""Enter your reply:""": u"""Enter your reply:""",


"""Error""": u"""Error""",


"""Events""": u"""Events""",


"""Expected traffic""": u"""Expected traffic""",


"""Failed to unregister""": u"""Failed to unregister""",


"""Failed to upload the photo to %(service_name)s""": u"""Failed to upload the photo to %(service_name)s""",


"""Flow result of %(user)s for %(flow)s""": u"""Flow result of %(user)s for %(flow)s""",


"""forms.click_button_to_test""": u"""Click the button to test your survey""",


"""forms.click_to_test_your_form""": u"""Tap this notification to test your survey""",


"""forms.max_submission_count_reached""": u"""The survey could not be submitted because you have already submitted it %(submission_count)s time(s)""",


"""forms.test_form""": u"""Test survey""",


"""forms.test_form_x""": u"""Test survey: %(title)s""",


"""Group chat""": u"""Group chat""",


"""http://www.ourcityapps.com""": u"""http://www.ourcityapps.com""",


"""i_agree_to_toc""": u"""I agree to the Terms and Conditions""",


"""If you cannot access the link above, you can paste the following address into your browser:""": u"""If you cannot access the link above, you can paste the following address into your browser:""",


"""Install %(other_app_name)s""": u"""Install %(other_app_name)s""",


"""Invalid download_url (%(url)s). It must be reachable over http or https.""": u"""Invalid download_url (%(url)s). It must be reachable over http or https.""",


"""Invite %(name)s to connect on %(app_name)s""": u"""Invite %(name)s to connect on %(app_name)s""",


"""Invite %(name)s""": u"""Invite %(name)s""",


"""Kind regards""": u"""Kind regards""",


"""Local""": u"""Local""",


"""Location: %(address)s""": u"""Location: %(address)s.""",


"""log_out""": u"""Log out""",


"""mdp_missing_address""": u"""The address stored in your MIDIGIPASS account is incomplete. Please configure your address in MYDIGIPASS and try again.""",


"""mdp_missing_eid_data""": u"""There is no eID data stored in your MIDIGIPASS account. Please configure your eID data in MYDIGIPASS and try again.""",


"""mdp_missing_email""": u"""There is no e-mail address stored in your MIDIGIPASS account. Please configure your e-mail address in MYDIGIPASS and try again.""",


"""mdp_missing_phone""": u"""There is no phone number stored in your MIDIGIPASS account. Please configure your phone number in MYDIGIPASS and try again.""",


"""mdp_missing_profile""": u"""The personal information stored in your MIDIGIPASS account is incomplete. Please complete your profile in MYDIGIPASS and try again.""",


"""mdp_missing_scopes""": u"""There is insufficient data available in your MYDIGIPASS account. The following data is missing: %(missing_data)s

Please complete your MYDIGIPASS account data and try again.

Also make sure you have the latest version of the \"MYDIGIPASS Authenticator for Mobile\" app.""",


"""merchant""": u"""Merchant""",


"""Merchants""": u"""Merchants""",


"""My services""": u"""My services""",


"""Nearby services""": u"""Nearby services""",


"""New job match""": u"""New job match""",


"""New job matches""": u"""New job matches""",


"""new_news_available""": u"""New news available""",


"""new_news_available_for_group""": u"""New news available for %(group)s""",


"""News about events""": u"""News about events""",


"""News hasn't been setup yet for this app""": u"""News hasn't been setup yet for this app""",


"""No events""": u"""No events""",


"""No matching service found""": u"""No matching service found.""",


"""No news yet""": u"""No news yet""",


"""No news""": u"""No news""",


"""No polls""": u"""No polls""",


"""No press""": u"""No press""",


"""No promotions""": u"""No promotions""",


"""No service found""": u"""No service found.""",


"""No traffic""": u"""No traffic""",


"""notify_service_location_tracking""": u"""%(service)s is tracking your location until %(until)s.""",


"""OCA""": u"""Our City App""",


"""open_link""": u"""Open %(link)s""",


"""password reset""": u"""password reset""",


"""payments.account_already_exists""": u"""An account with this currency (%(currency)s) already exists. Please choose another currency or another wallet type.""",


"""payments.cannot_verify_wallet_type""": u"""This type of wallet cannot not be validated.""",


"""payments.continue_adding_credit_card_info""": u"""To continue adding this credit card, you must enter the credit card information on an external website.""",


"""payments.currency_unknown""": u"""The currency of this wallet could not be determined.""",


"""payments.duplicate_wallet""": u"""A wallet with specified data already exists.""",


"""payments.enter_code_present_in_transaction_on_bank_account""": u"""Enter the code present in the transaction that was made to this bank account""",


"""payments.insufficient_funds""": u"""This wallet does not contain enough funds to commit the transaction.""",


"""payments.invalid_iban""": u"""Invalid IBAN number, please check if you entered it correctly.""",


"""payments.invalid_verification_code""": u"""Invalid verification code.""",


"""payments.permission_denied""": u"""You don't have permission to do this action.""",


"""payments.provider_not_found""": u"""Payment provider not found.""",


"""payments.ref""": u"""Ref.""",


"""payments.transaction_already_initiated""": u"""This transaction has already been started by another user.""",


"""payments.transaction_finished""": u"""This transaction has already been finished.""",


"""payments.transaction_not_found""": u"""Transaction not found.""",


"""payments.transaction_not_initiated""": u"""This transaction has not been initiated yet.""",


"""payments.unknown""": u"""An unknown error has occurred. Please try again later.""",


"""Phone number""": u"""Phone number""",


"""Please try again later.""": u"""Please try again later.""",


"""Please use this secure URL to reset your password within 5 days.""": u"""Please use this secure URL to reset your password within 5 days.""",


"""please_agree_to_toc""": u"""Please agree to the Terms and Conditions before continuing""",


"""please_review_updated_tac""": u"""Please review our updated Terms and Conditions before continuing""",


"""Polls""": u"""Polls""",


"""Press""": u"""Press""",


"""privacy-policy""": u"""Privacy Policy""",


"""Profile""": u"""Profile""",


"""Promotions in and around your city""": u"""Promotions in and around your city""",


"""Promotions in and around your community""": u"""Promotions in and around your community""",


"""Promotions""": u"""Promotions""",


"""read_the_toc_to_continue""": u"""Please read the Terms and Conditions to continue""",


"""Received location of %(name)s.

Accuracy: %(accuracy)sm""": u"""Received location of %(name)s.

Accuracy: %(accuracy)sm""",


"""received_password_reset_request_for_app""": u"""We have received your password reset request for %(app_name)s.""",


"""Regional""": u"""Regional""",


"""Reply""": u"""Reply""",


"""rogerthat-payment.account""": u"""{{ provider }} Account""",


"""rogerthat-payment.bank""": u"""Bank account""",


"""rogerthat-payment.creditcard""": u"""Credit card""",


"""Save""": u"""Save""",


"""Scan QR code to discover!""": u"""Scan QR code to discover!""",


"""Search results""": u"""Search results""",


"""Send reply""": u"""Send reply""",


"""Service %(name)s wants to connect with you via %(app_name)s.""": u"""Service %(name)s wants to connect to you via %(app_name)s.""",


"""service""": u"""Service""",


"""Services""": u"""Services""",


"""Show map""": u"""Show map""",


"""signup""": u"""Signup""",


"""Spaces are not allowed in an e-mail address""": u"""Spaces are not allowed in an e-mail address""",


"""Submit""": u"""Submit""",


"""successfully_unsubscribed_broadcast_type""": u"""You have been successfully unsubscribed from notifications with type \"%(notification_type)s\" of %(service)s.""",


"""tag""": u"""Tag""",


"""terms-and-conditions""": u"""Terms and Conditions""",


"""terms-and-conditions-service""": u"""Terms and Conditions""",


"""thank_you_for_using_app""": u"""Thank you for using %(app_name)s!""",


"""The latest news of your city""": u"""The latest news of your city""",


"""The latest news of your community""": u"""The latest news of your community""",


"""The scanned QR code is not supported by the %(app_name)s app""": u"""The scanned QR code is not supported by the %(app_name)s app""",


"""the_app_support_email_address_html""": u"""<a href=\"mailto:%(email)s\">%(app_name)s support</a>""",


"""the_app_team""": u"""The %(app_name)s Team""",


"""the_our_city_app_coach_email_address""": u"""coach@ourcityapps.com""",


"""the_our_city_app_coach_email_address_html""": u"""the <a href=\"mailto:%(email)s\">Our City Coach</a>""",


"""the_our_city_app_team""": u"""The Our City App Team""",


"""There are no events at this time""": u"""There are no events at this time""",


"""There are no local press articles at this time""": u"""There are no local press articles at this time""",


"""There are no polls at this time""": u"""There are no polls at this time""",


"""There are no promotions at this time""": u"""There are no promotions at this time""",


"""There is no e-mail address configured in your facebook account. Please use the e-mail based login.""": u"""There is no e-mail address configured in your facebook account. Please use the e-mail based login.""",


"""There is no news at this time""": u"""There is no news at this time""",


"""There is no traffic at this time""": u"""There is no traffic at this time""",


"""This service is not supported by the %(current_app_name)s app. Please install the %(other_app_name)s app.""": u"""This service is not supported by the %(current_app_name)s app. Please install the %(other_app_name)s app.""",


"""To reset your password, please enter your password twice on the page that opens.""": u"""To reset your password, please enter your password twice on the page that opens.""",


"""Traffic""": u"""Traffic""",


"""Trafic""": u"""Traffic""",


"""Unknown""": u"""Unknown""",


"""Unsubscribe""": u"""Unsubscribe""",


"""User %(name)s has requested to share your location.""": u"""User %(name)s has requested to share your location.""",


"""User %(name)s wants to get in touch with you via %(app_name)s.""": u"""%(name)s wants to get in touch with you via %(app_name)s.""",


"""user""": u"""User""",


"""user_data_download_duplicate""": u"""We sent a link to %(email)s. The easiest way to download your data might be to check your email on a computer.""",


"""user_data_download_ready_summary""": u"""Your data download is ready""",


"""user_data_download_started""": u"""Once we've finished creating your file, we'll send you an email letting you known it's complete and ready to be downloaded.
For security reasons, your file will be available to download for only a few days after you receive an email from us, so please monitor your email for our message.""",


"""We could not determine the location of %(name)s.""": u"""We could not determine the location of %(name)s.""",


"""Which type of broadcasts do you wish to receive?""": u"""Which type of broadcasts do you wish to receive?""",


"""Why do you wish to deactivate your account?""": u"""Why do you wish to deactivate your account?""",


"""Why do you wish to unsubscribe to this e-mail?""": u"""Why do you wish to unsubscribe to this e-mail?""",


"""You are already connected with %(name)s.""": u"""You are already connected with %(name)s.""",


"""You are now unsubscribed.""": u"""You are now unsubscribed.""",


"""You can not register with this e-mail address""": u"""You can not register with this e-mail address""",


"""You have been logged out on your request""": u"""You have been logged out on your request""",


"""Your account has been deleted on your request""": u"""Your account has been deleted on your request""",


"""Your city in the press""": u"""Your city in the press""",


"""Your community in the press""": u"""Your community in the press""",


"""Your device was unregistered because the same account was used to register the following device '%(device_name)s'""": u"""Your device was unregistered because the same account was used to register the following device '%(device_name)s'""",


"""Your upload is completed""": u"""Your upload is completed"""}


# ###########################################################################################

D["es"] = {


"""%(app_name)s has %(count)d new messages for you""": u"""%(app_name)s tiene %(count)d mensajes nuevos para ti""",


"""%(app_name)s has 1 new message for you""": u"""%(app_name)s tiene 1 mensaje nuevo para ti""",


"""%(app_name)s mobile registration""": u"""Registro %(app_name)s""",


"""%(name)s accepted your location sharing request.
Latest information:

Accuracy: %(accuracy)sm""": u"""%(name)s ha aceptado tu petición para compartir ubicación.
Información actualizada:

Precisión: %(accuracy)sm""",


"""%(name)s accepted your location sharing request. Unfortunately we could not determine his/her location at this moment.""": u"""%(name)s ha aceptado tu petición para compartir su ubicación. Desafortunadamente, no se puede establecer tu ubicación en este momento.""",


"""%(name)s added a personal note:
%(message)s""": u"""%(name)s ha añadido una nota personal:
%(message)s""",


"""%(name)s declined your request to track his/her location.""": u"""%(name)s ha rechazado tu petición para establecer su ubicación.""",


"""%(name)s does not have a device which supports location tracking.""": u"""%(name)s no dispone de un dispositivo con soporte para localización geográfica.""",


"""%(name)s invites you to the %(app_name)s app!""": u"""%(name)s te ha invitado a la app %(app_name)s!""",


"""%(name)s just joined %(app_name)s, and we found you in his facebook friends list!""": u"""%(name)s se ha unido a %(app_name)s. Te hemos localizado en la lista de contactos de Facebook.""",


"""%(name_or_email)s added a personal note:

%(message)s""": u"""%(name_or_email)s ha añadido una nota personal:

%(message)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.

About %(service_name)s:
%(service_description)s""": u"""%(user_name)s te recomienda conectarte a %(service_name)s en %(app_name)s.

Acerca de %(service_name)s:
%(service_description)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.""": u"""%(user_name)s te recomienda conectarte a %(service_name)s en %(app_name)s.""",


"""_automatic_detection_invitation""": u"""Hola,
Acabamos de bienvenida a nuestra empresa.
¿Sabías que también ofrecemos nuestros servicios a través de la aplicación de %(app_name)s?
Haga clic en el botón \"Añadir a isso app\" para añadirnos a su lista de servicios.
Un cordial saludo, %(service_name)s.""",


"""_enable_location_services_ios7""": u"""Para activar Localización:
1. Deje el %(app_name)s app e abra el Ajustes app
2. Pulse en Privacidad  > Localización
3. Búsqueda de %(app_name)s y alternar el interruptor en ON""",


"""_enable_location_services_ios8""": u"""Para activar Localización:
1. Deje el %(app_name)s app e abra el Ajustes app
2. Pulse en Privacidad  > Localización
3. Búsqueda de %(app_name)s y alternar el acceso a ubicación en 'Siempre'""",


"""_friend_denied_location_services""": u"""%(name)s ha desactivado localización del %(app_name)s app""",


"""_friendship_accepted""": u"""Hola %(name)s,
%(friend_name)s está ahora conectado con usted.
Ya puede gozar de esta experiencia.""",


"""_friendship_established""": u"""Hola %(name)s,
Usted está ahora en contacto con %(friend_name)s.
¡Ya puede gozar de esta experiencia!""",


"""_friendship_request_failed""": u"""Hola %(name)s,
Su petición para conectarse con %(friend_name)s ha fallado.
Presione el botón Invitar para invitar a %(friend_name)s.""",


"""_invited_too_often""": u"""Hola %(name)s,
Ha invitado a %(friend_email)s en tres ocasiones.
Para prevenir el correo Spam, %(app_name)s no enviará más invitaciones a este contacto.""",


"""_invited_too_often_this_week""": u"""Hola %(name)s,
Ya ha invitado a %(friend_email)s anteriormente esta semana.
Para prevenir el correo Spam, %(app_name)s no enviará más invitaciones a este contacto.""",


"""_invited_yourself""": u"""Hola %(name)s,
Ha intentado añadirse como contacto usted mismo.
Lo sentimos, pero esto no es posible.""",


"""_invitee_was_already_friend""": u"""Hola %(name)s,
Ha intentado invitar a %(friend_email)s . Este contacto ya se encuentra en su lista de contactos.""",


"""_location_services_denied""": u"""%(name)s solicitado su ubicación, pero hay localización con discapacidad para el %(app_name)s app.""",


"""_unsupported_attachment_file_type""": u"""Tipo de archivo no admitido para accesorio %(url)s
Sólo apoyamos archivos pdf, jpeg y png""",


"""_welcome_message""": u"""Bienvenido a la aplicación %(app_name)s!

Conéctate a sus proveedores preferidos, asociaciones, instituciones y amigos y empieza a comunicarte.

Feliz mensajería!

Solicita tu propia aplicación como un proveedor de negocio, asociación o atención sanitaria local utilizando el botón de abajo o póngase en contacto con nosotros en %(contact_email_address)s""",


"""A-Z""": u"""A-Z""",


"""About""": u"""Info""",


"""Accept invitation""": u"""Aceptar invitación""",


"""account_already_deactivated""": u"""(Ya) No estas suscrito a la app %(app_name)s con esta cuenta (%(account)s).""",


"""account_already_disconnected_from_service""": u"""(Ya) No estas suscrito a %(service_name)s.""",


"""Add to my services""": u"""Añadir a isso app""",


"""Address""": u"""Dirección""",


"""An unknown error has occurred""": u"""Un error desconocido a ocurrido""",


"""app""": u"""App""",


"""app_website_rogerthat""": u"""https://rogerth.at""",


"""association""": u"""Asociación""",


"""Associations""": u"""Asociaciones""",


"""broadcast_reminder_explanation""": u"""Estas recibiendo esta notificación porque estas suscrito a: %(broadcast_type)s'""",


"""Can not connect to server""": u"""No es posible conectar con el servidor""",


"""Cancel""": u"""Cancelar""",


"""Care""": u"""Salud""",


"""Community Services""": u"""Servicios comunitarios""",


"""community_service""": u"""Servicio comunitario""",


"""continue""": u"""Continuar""",


"""Could not determine file type for attachment %(url)s""": u"""No pudo determinar el tipo de archivo adjunto %(url)s""",


"""Could not download attachment %(url)s""": u"""No se pudo descargar el adjunto %(url)s""",


"""date""": u"""Fecha""",


"""Deactivate""": u"""Desactivar""",


"""dear_name""": u"""Estimado %(name)s""",


"""Decline invitation""": u"""Rechazar invitación""",


"""Discover our new app""": u"""Descubre nuestra app""",


"""Distance: %(distance)s km""": u"""Distancia: %(distance)s km""",


"""E-mail address""": u"""Dirección de correo electrónico""",


"""eID data""": u"""DNI electronico""",


"""Enter your reply:""": u"""Introduzca su respuesta:""",


"""Error""": u"""Error""",


"""Events""": u"""Eventos""",


"""Failed to unregister""": u"""Error al anular el registro""",


"""Failed to upload the photo to %(service_name)s""": u"""Error al cargar la foto en %(service_name)s""",


"""Flow result of %(user)s for %(flow)s""": u"""Resultado de Flujo %(user)s para %(flow)s""",


"""Group chat""": u"""Chat de grupo""",


"""http://www.ourcityapps.com""": u"""http://www.ourcityapp.es""",


"""Install %(other_app_name)s""": u"""Instalar %(other_app_name)s""",


"""Invalid download_url (%(url)s). It must be reachable over http or https.""": u"""Link inválido (%(url)s). Debe ser accesible por http o https.""",


"""Invite %(name)s to connect on %(app_name)s""": u"""Invitar a %(name)s a conectarse con %(app_name)s""",


"""Invite %(name)s""": u"""Invitar a %(name)s""",


"""Kind regards""": u"""Saludos cordiales""",


"""Location: %(address)s""": u"""Ubicación: %(address)s.""",


"""log_out""": u"""Salir""",


"""mdp_missing_address""": u"""La dirección almacenada en su cuenta MIDIGIPASS es incompleta. Por favor, configure su dirección en MYDIGIPASS y vuelve a intentarlo.""",


"""mdp_missing_eid_data""": u"""No hay datos de identificación electrónica almacenados en su cuenta MIDIGIPASS. Por favor, configure sus datos de identificación electrónica en MYDIGIPASS y vuelve a intentarlo.""",


"""mdp_missing_email""": u"""No hay una dirección de correo electrónico almacenado en su cuenta MIDIGIPASS. Por favor, configure su dirección de e-mail en MYDIGIPASS y vuelve a intentarlo.""",


"""mdp_missing_phone""": u"""No hay un número de teléfono almacenado en su cuenta MIDIGIPASS. Por favor, configure su número de teléfono en MYDIGIPASS y vuelve a intentarlo.""",


"""mdp_missing_profile""": u"""La información personal almacenada en su cuenta MIDIGIPASS es incompleta. Por favor completar su perfil en MYDIGIPASS y vuelve a intentarlo.""",


"""mdp_missing_scopes""": u"""No hay suficientes datos disponibles en su cuenta MYDIGIPASS. Los siguientes datos no se encuentra: %(missing_data)s
Por favor, complete sus datos de la cuenta MYDIGIPASS y vuelve a intentarlo. También asegúrese de que este usando la última versión de la \"MYDIGIPASS Authenticator for Mobile\" de la aplicación.""",


"""merchant""": u"""Comerciante""",


"""Merchants""": u"""Comerciantes""",


"""My services""": u"""Mis servicios""",


"""Nearby services""": u"""Servicios cercanos""",


"""No matching service found""": u"""No se encontraron resultados.""",


"""No service found""": u"""No se encontraron resultados.""",


"""notify_service_location_tracking""": u"""%(service)s es el seguimiento de su ubicación hasta las %(until)s.""",


"""OCA""": u"""Our City App""",


"""open_link""": u"""Abra %(link)s""",


"""Phone number""": u"""Número de teléfono""",


"""Please try again later.""": u"""Inténtelo de nuevo más tarde.""",


"""Profile""": u"""Perfil""",


"""Promotions""": u"""Patrocinios""",


"""Received location of %(name)s.

Accuracy: %(accuracy)sm""": u"""Se ha recibido la ubicación de %(name)s.

Precisión: %(accuracy)sm""",


"""Reply""": u"""Responder""",


"""rogerthat-payment.creditcard""": u"""Tarjeta de crédito""",


"""Save""": u"""Guardar""",


"""Scan QR code to discover!""": u"""Escanear un código QR para buscar!""",


"""Search results""": u"""Resultados de la búsqueda""",


"""Send reply""": u"""Envíe respuesta""",


"""Service %(name)s wants to connect with you via %(app_name)s.""": u"""Service %(name)s desea conectarse con usted a través de %(app_name)s.""",


"""service""": u"""Servicio""",


"""Services""": u"""Servicios""",


"""Show map""": u"""Mostrar mapa""",


"""Spaces are not allowed in an e-mail address""": u"""No se permiten espacios en una dirección de correo electrónico""",


"""Submit""": u"""Enviar""",


"""successfully_unsubscribed_broadcast_type""": u"""Has sido dado de baja exitosamente de las notificaciones del tipo \"%(notification_type)s\" de %(service)s.""",


"""The scanned QR code is not supported by the %(app_name)s app""": u"""El código QR ​​escaneado no está soportado por el %(app_name)s app""",


"""the_app_support_email_address_html""": u"""<a href=\"mailto:%(email)s\">Soporte de %(app_name)s</a>""",


"""the_app_team""": u"""El equipo de %(app_name)s""",


"""the_our_city_app_coach_email_address""": u"""coach@ourcityapps.com""",


"""the_our_city_app_coach_email_address_html""": u"""El <a href=\"mailto:%(email)s\">entrenador de Our City</a>""",


"""the_our_city_app_team""": u"""El equipo de Our City App""",


"""There is no e-mail address configured in your facebook account. Please use the e-mail based login.""": u"""No hay dirección de correo electrónico configurado en su cuenta de Facebook. Por favor, inicie sesion con su correo electrónico.""",


"""This service is not supported by the %(current_app_name)s app. Please install the %(other_app_name)s app.""": u"""Este servicio no es compatible con el %(current_app_name)s app. Por favor, instalar el %(other_app_name)s app.""",


"""Unknown""": u"""Desconocido""",


"""Unsubscribe""": u"""Darse de baja""",


"""User %(name)s has requested to share your location.""": u"""User %(name)s ha solicitado compartir su ubicación.""",


"""User %(name)s wants to get in touch with you via %(app_name)s.""": u"""%(name)s desea contactar contigo a través de %(app_name)s.""",


"""user""": u"""Usuario""",


"""We could not determine the location of %(name)s.""": u"""No se puede establecer la ubicación de %(name)s.""",


"""Which type of broadcasts do you wish to receive?""": u"""¿Qué tipo de notificaciones deseas recibir?""",


"""Why do you wish to deactivate your account?""": u"""¿Deseas desactivar tu cuenta?""",


"""Why do you wish to unsubscribe to this e-mail?""": u"""¿Por qué desea cancelar su suscripción a este e-mail?""",


"""You are already connected with %(name)s.""": u"""Ya estás conectado con %(name)s.""",


"""You are now unsubscribed.""": u"""Ahora está de baja.""",


"""You can not register with this e-mail address""": u"""No se puede registrar con esta dirección de correo electrónico"""}


# ###########################################################################################

D["fr"] = {


"""%(app_name)s has %(count)d new messages for you""": u"""%(app_name)s a %(count)d de nouveaux messages pour vous""",


"""%(app_name)s has 1 new message for you""": u"""%(app_name)s a 1 nouveau message pour vous""",


"""%(app_name)s mobile registration""": u"""Votre inscription %(app_name)s""",


"""%(name)s accepted your location sharing request.
Latest information:

Accuracy: %(accuracy)sm""": u"""%(name)s partage désormais sa position avec vous.
Information récente:

Précision: %(accuracy)sm""",


"""%(name)s accepted your location sharing request. Unfortunately we could not determine his/her location at this moment.""": u"""%(name)s a accepté votre requête pour partager sa position. Malheureusement, nous ne pouvons pas déterminer sa position en ce moment.""",


"""%(name)s added a personal note:
%(message)s""": u"""%(name)s a ajouté un message personnel:
%(message)s""",


"""%(name)s declined your request to track his/her location.""": u"""%(name)s a refusé votre requête.""",


"""%(name)s does not have a device which supports location tracking.""": u"""%(name)s n'a pas un appareil portable qui peut donner la position.""",


"""%(name)s invites you to the %(app_name)s app!""": u"""%(name)s vous invite à utiliser l'application %(app_name)s!""",


"""%(name)s just joined %(app_name)s, and we found you in his facebook friends list!""": u"""%(name)s a rejoint %(app_name)s, et on vous a trouvé dans ses amis Facebook.""",


"""%(name_or_email)s added a personal note:

%(message)s""": u"""%(name_or_email)s a ajouté un message personnel:

%(message)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.

About %(service_name)s:
%(service_description)s""": u"""%(user_name)s vous recommande d'utiliser le service %(service_name)s avec %(app_name)s.

Info sur %(service_name)s:
%(service_description)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.""": u"""%(user_name)s vous recommande d'utiliser le service %(service_name)s avec %(app_name)s.""",


"""_automatic_detection_invitation""": u"""Bonjour,

Nous avons le plaisir de vous accueillir dans notre société.
Saviez-vous que vous pouvez accéder à l'ensemble des services proposés dans notre ville via l'application %(app_name)s?
Cliquez sur le bouton \"Ajouter cette application\" pour accéder à nos services dans l'application.

A bientôt,
%(service_name)s.""",


"""_enable_location_services_ios7""": u"""Pour activer le service de localisation:
1. Laissez le %(app_name)s app et allez dans les Réglages
2. Allez dans Confidentialité > Service de localisation
3. Recherchez %(app_name)s et basculez l'interrupteur sur ON""",


"""_enable_location_services_ios8""": u"""Pour activer le service de localisation:
1. Laissez le %(app_name)s app et allez dans les Réglages
2. Allez dans Confidentialité > Service de localisation
3. Recherchez %(app_name)s et modifiez l'accès à votre position sur «Toujours»""",


"""_friend_denied_location_services""": u"""%(name)s a désactivé le service de localisation pour l'application %(app_name)s""",


"""_friendship_accepted""": u"""Bonjour %(name)s,
%(friend_name)s est désormais connecté à vous.
Joyeux messages  !""",


"""_friendship_established""": u"""Bonjour %(name)s,
Maintenant vous êtes amis avec %(friend_name)s.
Joyeux messages!""",


"""_friendship_request_failed""": u"""Bonjour %(name)s,
Votre demande de connexion avec %(friend_name)s a échoué.
Appuyez à nouveau sur le bouton pour inviter %(friend_name)s.""",


"""_invited_too_often""": u"""Bonjour %(name)s,
Vous avez invité %(friend_email)s 3 fois.
Pour éviter les spams, %(app_name)s ne vous enverra plus d'invitations.""",


"""_invited_too_often_this_week""": u"""Cher %(name)s,
Vous avez déjà invité %(friend_email)s durant cette semaine.
Pour éviter les spams, %(app_name)s ne va plus envoyer des invitations à %(friend_email)s.""",


"""_invited_yourself""": u"""Bonjour %(name)s,
Vous avez essayé de devenir ami avec vous-même.
Malheureusement ce n'est pas possible.""",


"""_invitee_was_already_friend""": u"""Bonjour %(name)s,
Vous avez invité %(friend_email)s qui est déjà dans votre liste d'amis.""",


"""_location_services_denied""": u"""%(name)s a demandé votre position, mais vous avez désactivé le service de localisation pour l'application %(app_name)s.""",


"""_unsupported_attachment_file_type""": u"""Le fichier %(url)s n'est pas pris en charge.
Sont supportés les formats pdf, jpeg et png""",


"""A-Z""": u"""A-Z""",


"""About""": u"""Au sujet de""",


"""Accept invitation""": u"""Accepter l'invitation""",


"""account_already_deactivated""": u"""Vous n'êtes pas abonné (plus) à l'application de %(app_name)s avec ce compte (%(account)s).""",


"""account_already_disconnected_from_service""": u"""Vous n'êtes pas abonné (plus) pour %(service_name)s.""",


"""Add to my services""": u"""Ajouter cette application""",


"""Address""": u"""Adresse""",


"""All the news of our app""": u"""Toutes les nouvelles de notre application""",


"""An unknown error has occurred""": u"""Une erreur inconnue s'est produite""",


"""App news""": u"""Nouvelles de l'application""",


"""app""": u"""App""",


"""app_website_rogerthat""": u"""https://rogerth.at""",


"""around_you""": u"""Autour de toi""",


"""association""": u"""Association""",


"""Associations""": u"""Associations""",


"""broadcast_reminder_explanation""": u"""Vous recevez cette notification, car vous êtes abonné à: %(broadcast_type)s""",


"""Can not connect to server""": u"""Impossible de se connecter au serveur""",


"""Cancel""": u"""Annuler""",


"""Care""": u"""Santé""",


"""City news""": u"""Nouvelles de la ville""",


"""Community news""": u"""Nouvelles de la ville""",


"""Community Services""": u"""Ma ville""",


"""continue""": u"""Continuer""",


"""Could not determine file type for attachment %(url)s""": u"""Impossible de déterminer le type de fichier pour l'attachement %(url)s""",


"""Could not download attachment %(url)s""": u"""Impossible de télécharger l'attachement %(url)s""",


"""date""": u"""Date""",


"""Deactivate""": u"""Désactiver""",


"""dear_name""": u"""Cher %(name)s""",


"""Decline invitation""": u"""Refuser l'invitation""",


"""Discover our new app""": u"""Découvrez notre application""",


"""Distance: %(distance)s km""": u"""Distance: %(distance)s km""",


"""E-mail address""": u"""Adresse e-mail""",


"""eID data""": u"""Données eID""",


"""Enter your reply:""": u"""Entrez votre réponse:""",


"""Error""": u"""Erreur""",


"""Events""": u"""Evénements""",


"""Expected traffic""": u"""Trafic attendu""",


"""Failed to unregister""": u"""Impossible d'annuler l'inscription""",


"""Failed to upload the photo to %(service_name)s""": u"""Impossible de télécharger la photo vers %(service_name)s""",


"""Flow result of %(user)s for %(flow)s""": u"""Résultat du flux de %(user)s des %(flow)s""",


"""Group chat""": u"""Discussion de groupe""",


"""http://www.ourcityapps.com""": u"""http://www.villeconnectee.com""",


"""Install %(other_app_name)s""": u"""Installez %(other_app_name)s""",


"""Invalid download_url (%(url)s). It must be reachable over http or https.""": u"""Hyperlink invalide (%(url)s). Il doit être accessible via http ou https.""",


"""Invite %(name)s to connect on %(app_name)s""": u"""Inviter %(name)s à se connecter à %(app_name)s""",


"""Invite %(name)s""": u"""Inviter %(name)s""",


"""Kind regards""": u"""Bien Cordialement""",


"""Local""": u"""Local""",


"""Location: %(address)s""": u"""La position: %(address)s.""",


"""log_out""": u"""Se déconnecter""",


"""mdp_missing_address""": u"""L'adresse configurée dans votre compte MYDIGIPASS est incomplète. S'il vous plaît configurez votre adresse à MYDIGIPASS et essayez à nouveau.""",


"""mdp_missing_eid_data""": u"""Il n'y a pas de données d'identité électroniques configurées dans votre compte NYDIGIPASS. S'il vous plaît configurer vos données eID dans un MYDIGIPASS essayer à nouveau.""",


"""mdp_missing_email""": u"""Il n'y a aucune adresse email configurée dans votre compte MIDIGIPASS. S'il vous plaît configurez votre adresse e-mail à MYDIGIPASS et essayez à nouveau.""",


"""mdp_missing_phone""": u"""Il n'y a aucun numéro de téléphone configurée dans votre compte MYDIGIPASS. S'il vous plaît configurez votre numéro de téléphone à MYDIGIPASS et essayez à nouveau.""",


"""mdp_missing_profile""": u"""Les infomations personnelles configurées dans votre compte MYDIGIPASS sont incomplètes. S'il vous plaît configurez votre profil à MYDIGIPASS et essayez à nouveau.""",


"""mdp_missing_scopes""": u"""Il n'y a pas suffisamment de données disponibles dans votre compte MYDIGIPASS. Les données suivantes manquent: %(missing_data)s



S'il vous plaît remplir vos données de compte MYDIGIPASS et essayez à nouveau.



Assurez-vous également que vous avez la dernière version de l'application \"MYDIGIPASS Authenticator for mobile\".""",


"""merchant""": u"""Commerçant""",


"""Merchants""": u"""Commerces""",


"""My services""": u"""Mes services""",


"""Nearby services""": u"""Services dans votre quartier""",


"""new_news_available""": u"""Nouvelles nouvelles disponibles""",


"""new_news_available_for_group""": u"""Nouvelles nouvelles disponibles pour %(group)s""",


"""News about events""": u"""Nouvelles sur les événements""",


"""News hasn't been setup yet for this app""": u"""News n'a pas encore été configuré pour cette application""",


"""No events""": u"""Pas d'événements""",


"""No matching service found""": u"""Pas de résultats.""",


"""No news yet""": u"""Pas encore de nouvelles""",


"""No news""": u"""Pas de nouvelles""",


"""There is no news at this time""": u"""Il n'y a pas de nouvelles en ce moment""",


"""Press""": u"""Presse""",


"""Current polls""": u"""Sondages en cours""",


"""No polls""": u"""Pas de sondages""",


"""Polls""": u"""Sondages""",


"""There are no polls at this time""": u"""Il n'y a pas de sondages pour le moment""",


"""No press""": u"""Pas de presse""",


"""No promotions""": u"""Pas de promotions""",


"""No service found""": u"""Pas de résultats.""",


"""No traffic""": u"""Pas de trafic""",


"""notify_service_location_tracking""": u"""%(service)s suit votre position jusqu'à %(until)s.""",


"""OCA""": u"""Ville Connectée""",


"""open_link""": u"""Ouvrir %(link)s""",


"""Phone number""": u"""Numéro de téléphone""",


"""Please try again later.""": u"""Prière de recommencer plus tard.""",


"""Profile""": u"""Profil""",


"""Promotions in and around your city""": u"""Promotions dans et autour de votre ville""",


"""Promotions in and around your community""": u"""Promotions dans et autour de votre ville""",


"""Promotions""": u"""Promotions""",


"""Received location of %(name)s.

Accuracy: %(accuracy)sm""": u"""La position de %(name)s a été reçue.

Exactitude: %(accuracy)sm""",


"""Regional""": u"""Régional""",


"""Reply""": u"""Répondre""",


"""rogerthat-payment.creditcard""": u"""Carte de crédit""",


"""Save""": u"""Sauvegarder""",


"""Scan QR code to discover!""": u"""Scanner un code QR pour découvrir!""",


"""Search results""": u"""Résultats de la recherche""",


"""Send reply""": u"""Envoyer la réponse""",


"""Service %(name)s wants to connect with you via %(app_name)s.""": u"""Service %(name)s veut se connecter à vous via %(app_name)s.""",


"""Services""": u"""Services""",


"""Show map""": u"""Ouvrir la carte""",


"""Spaces are not allowed in an e-mail address""": u"""Les espaces ne sont pas autorisés dans une adresse e-mail""",


"""Submit""": u"""Envoyer""",


"""successfully_unsubscribed_broadcast_type""": u"""Vous avez été désabonné des notifications de type «%(notification_type)s» de %(service)s.""",


"""The latest news of your city""": u"""Les dernières nouvelles de votre ville""",


"""The latest news of your community""": u"""Les dernières nouvelles de votre ville""",


"""The scanned QR code is not supported by the %(app_name)s app""": u"""Le code QR numérisé n'est pas supporté par l'app de %(app_name)s""",


"""the_app_support_email_address_html""": u"""<a href=\"mailto:%(email)s\">soutien %(app_name)s</a>""",


"""the_app_team""": u"""L'équipe de %(app_name)s""",


"""the_our_city_app_coach_email_address""": u"""coach@ourcityapps.com""",


"""the_our_city_app_coach_email_address_html""": u"""le <a href=\"mailto:%(email)s\">Coach de Ville Connectée</a>""",


"""the_our_city_app_team""": u"""L'équipe Ville Connectée""",


"""There are no events at this time""": u"""Il n'y a pas d'événements en ce moment""",


"""There are no local press articles at this time""": u"""Il n'y a pas d'articles de presse locale pour le moment""",


"""There are no promotions at this time""": u"""Il n'y a pas de promotions pour le moment""",


"""There is no e-mail address configured in your facebook account. Please use the e-mail based login.""": u"""Il n'y a aucune adresse email configurée dans votre compte facebook ou vous n'avez pas donné les autorisations pour accéder à votre email. Merci de choisir la connexion via email.""",


"""There is no traffic at this time""": u"""Il n'y a pas de trafic en ce moment""",


"""This service is not supported by the %(current_app_name)s app. Please install the %(other_app_name)s app.""": u"""Ce service n'est pas supporté par l'app de %(current_app_name)s.  S'il vous plaît installez l'app %(other_app_name)s app.""",


"""Traffic""": u"""Trafic""",


"""Trafic""": u"""Trafic""",


"""Unknown""": u"""Inconnu""",


"""Unsubscribe""": u"""Désinscrire""",


"""User %(name)s has requested to share your location.""": u"""%(name)s a envoyé une demande pour que vous partagiez votre position.""",


"""User %(name)s wants to get in touch with you via %(app_name)s.""": u"""%(name)s veut communiquer avec vous via %(app_name)s.""",


"""user""": u"""Utilisateur""",


"""We could not determine the location of %(name)s.""": u"""Nous n'avons pas pu déterminer la position de %(name)s.""",


"""Which type of broadcasts do you wish to receive?""": u"""Quel type de médias souhaitez-vous recevoir?""",


"""Why do you wish to deactivate your account?""": u"""Pourquoi souhaitez-vous désactiver votre compte ?""",


"""Why do you wish to unsubscribe to this e-mail?""": u"""Pourquoi voulez-vous vous désabonner à cet e-mail?""",


"""You are already connected with %(name)s.""": u"""Vous êtes déjà connecté avec %(name)s.""",


"""You are now unsubscribed.""": u"""Vous êtes maintenant désinscrit.""",


"""You can not register with this e-mail address""": u"""Vous ne pouvez pas vous inscrire à cette adresse e-mail""",


"""Your city in the press""": u"""Votre ville dans la presse""",


"""Your community in the press""": u"""Votre ville dans la presse"""}


# ###########################################################################################

D["nl"] = {
"""starting_this_week""": u"""Startende deze week""",
"""app_jobs_title""": u"""Welkom bij JOBS!""",
"""app_jobs_description""": u"""Op zoek naar een nieuwe job-uitdaging? Voortaan vind je hier alle vacatures van lokale ondernemers, beginnende met die uit jouw rechtsreekse omgeving. Swipe heel eenvoudig door onze lokale & regionale jobaanbiedingen, aangevuld met alle vacatures van over heel Vlaanderen via de integratie met VDAB. Stel je voorkeuren in & ga aan de slag. - Succes!""",
"""at_least_one_job_domain_required""": u"""Er is minimaal één functiedomein vereist""",
"""job_info_text""": u"""Laat uw toekomstige werkgever weten waarom u geïnteresseerd bent in deze job. Deze zal uw naam, email adres en avatar te zien krijgen, tenzij U 'Anoniem' aan zet.""",
"""at_least_one_contract_type_required""": u"""Er is minimaal één type contract vereist""",
"""open_chat""": u"""Chat openen...""",
"""saved""": u"""Opgeslagen""",
"""save""": u"""Opslaan""",
"""update_app_to_use_feat""": u"""U moet de app updaten om deze functie te kunnen gebruiken.""",
"""gipod_notification_msg""": u"""U zal vanaf nu elke zondag een berichtje ontvangen met hinder in uw buurt.""",
"""gipod_notification_disabled_msg""": u"""U zal geen berichtje meer ontvangen op zondag met hinder in uw buurt.""",
"""hindrance_around_you""": u"""Hinder rondom u""",
"""no_hindrance_at_location""": u"""#### Geen hinder\n\nEr is geen hinder op deze locatie. Zoom uit op de map om meer te kunnen zien.""",
"""next_x_days""": u"""Volgende %(days)s dagen""",
"""all""": u"""Alle""",
"""Reported""": u"""Gemeld""",
"""In Progress""": u"""In behandeling""",
"""Resolved""": u"""Opgelost""",
"""Call""": u"""Bellen""",
"""Directions""": u"""Routebeschrijving""",
"""Saved""": u"""Bewaard""",


"""reports_around_you""": u"""Meldingen rondom u""",
"""no_reports_at_location""": u"""#### Geen meldingen.\n\nEr zijn geen meldingen op deze locatie. Zoom uit op de map om meer te kunnen zien.""",

"""services_around_you""": u"""Diensten rondom u""",
"""no_services_at_location""": u"""#### Geen diensten.\n\nEr zijn geen diensten op deze locatie. Zoom uit op de map om meer te kunnen zien.""",

"""open""": u"""Open""",
"""closed""": u"""Gesloten""",
"""always_closed""": u"""Altijd gesloten""",
"""open_24_hours""": u"""24u open""",
"""open_until""": u"""Open tot %(time)s""",
"""opens_on_time""": u"""Opent om %(time)s""",
"""opens_on_day_and_time""": u"""Opent op %(day)s om %(time)s""",

"""New location updates""": u"""Nieuwe locatie updates""",
"""%(name)s this week there are %(count)s new works, festivities or events planned around you""": u"""%(name)s deze week zijn er %(count)s nieuwe werken, festiviteiten of manifestaties gepland rondom u""",

"""%(app_name)s has %(count)d new messages for you""": u"""%(app_name)s heeft %(count)d nieuwe berichten voor u""",


"""%(app_name)s has 1 new message for you""": u"""%(app_name)s heeft 1 nieuw bericht voor u""",


"""%(app_name)s mobile registration""": u"""%(app_name)s mobiele registratie""",


"""%(count)s new matches""": u"""%(count)s nieuwe vacatures""",


"""%(name)s accepted your location sharing request.
Latest information:

Accuracy: %(accuracy)sm""": u"""%(name)s deelt vanaf nu zijn locatie met u.
Meest recente informatie:

Nauwkeurigheid: %(accuracy)sm""",


"""%(name)s accepted your location sharing request. Unfortunately we could not determine his/her location at this moment.""": u"""%(name)s deelt vanaf nu zijn/haar locatie met u.
Helaas konden we zijn/haar locatie nu niet bepalen.""",


"""%(name)s added a personal note:
%(message)s""": u"""%(name)s heeft een persoonlijke boodschap toegevoegd:
%(message)s""",


"""%(name)s declined your request to track his/her location.""": u"""%(name)s heeft uw verzoek geweigerd om zijn/haar locatie te bepalen.""",


"""%(name)s does not have a device which supports location tracking.""": u"""Plaatsbepaling is niet ondersteund op het toestel van %(name)s.""",


"""%(name)s invites you to the %(app_name)s app!""": u"""%(name)s nodigt u uit in de %(app_name)s app!""",


"""%(name)s just joined %(app_name)s, and we found you in his facebook friends list!""": u"""%(name)s gebruikt nu ook %(app_name)s, en we vonden u tussen zijn/haar Facebook vrienden.""",


"""%(name_or_email)s added a personal note:

%(message)s""": u"""%(name_or_email)s heeft een persoonlijke boodschap toegevoegd:

%(message)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.

About %(service_name)s:
%(service_description)s""": u"""%(user_name)s beveelt je de dienst %(service_name)s aan op %(app_name)s.

Over %(service_name)s:
%(service_description)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.""": u"""%(user_name)s beveelt u de smartphone dienst %(service_name)s aan op %(app_name)s.""",


"""_automatic_detection_invitation""": u"""Hallo,

We heten u welkom in onze zaak.
Wist u dat wij ook diensten via de %(app_name)s app aanbieden?
Klik op de \"Voeg toe aan deze app\" knop om ons toe te voegen aan uw lijst met diensten.

Met vriendelijke groeten,
%(service_name)s""",


"""_enable_location_services_ios7""": u"""Om locatievoorzieningen in te schakelen:
1. Verlaat de %(app_name)s app en ga naar de Instellingen app
2. Tik op Privacy > locatievoorzieningen
3. Zoek naar %(app_name)s en zet de schakelaar aan""",


"""_enable_location_services_ios8""": u"""Om locatievoorzieningen in te schakelen:
1. Verlaat de %(app_name)s app en ga naar de Instellingen app
2. Tik op Privacy > locatievoorzieningen
3. Zoek naar %(app_name)s en zet toegang tot locatie op 'Altijd'""",


"""_friend_denied_location_services""": u"""%(name)s heeft locatievoorzieningen uitgeschakeld voor de %(app_name)s app""",


"""_friendship_accepted""": u"""Beste %(name)s,

U bent vanaf nu bevriend met %(friend_name)s.""",


"""_friendship_established""": u"""Beste %(name)s,

U bent vanaf nu bevriend met %(friend_name)s.""",


"""_friendship_request_failed""": u"""Beste %(name)s,

Uw verzoek om met %(friend_name)s te communiceren, is mislukt.
Druk op de knop om het opnieuw te proberen.""",


"""_invited_too_often""": u"""Beste %(name)s,

U hebt %(friend_email)s 3 keer een vriendschapsverzoek gestuurd.
Om spam te vermijden zal %(app_name)s geen bijkomende uitnodigingen versturen.""",


"""_invited_too_often_this_week""": u"""Beste %(name)s,

U heeft eerder deze week %(friend_email)s al eens een vriendschapsverzoek gestuurd.
Om spam te vermijden zal %(app_name)s geen bijkomende uitnodigingen versturen.""",


"""_invited_yourself""": u"""Beste %(name)s,

U probeerde een vriendschapsverzoek naar uzelf te versturen.
Dat wordt niet ondersteund.""",


"""_invitee_was_already_friend""": u"""Beste %(name)s,

U probeerde een vriendschapsverzoek te versturen naar %(friend_email)s waarmee u al bevriend bent.""",


"""_location_services_denied""": u"""%(name)s heeft jouw locatie opgevraagd, maar je hebt locatievoorzieningen uitgeschakeld voor de %(app_name)s app.""",


"""_unsupported_attachment_file_type""": u"""Niet ondersteund bestandstype voor bijlage %(url)s
Wij ondersteunen enkel pdf, jpeg en png bestanden""",


"""_welcome_message""": u"""Welkom bij de %(app_name)s app!

Voeg de apps van uw favoriete winkels en verenigingen toe, connecteer met uw vrienden en stuur berichten.

Veel succes!

Vraag als lokale ondernemer, vereniging of zorgverstrekker uw eigen applicatie in de %(app_name)s app aan door op onderstaande knop te drukken of contacteer ons op %(contact_email_address)s""",


"""A-Z""": u"""A-Z""",


"""About""": u"""Info""",


"""Accept invitation""": u"""Verzoek aanvaarden""",


"""account_already_deactivated""": u"""U bent niet (meer) ingeschreven op de %(app_name)s met dit account (%(account)s).""",


"""account_already_disconnected_from_service""": u"""U bent niet (meer) ingeschreven op %(service_name)s.""",


"""Add to my services""": u"""Voeg toe aan deze app""",


"""Address""": u"""Adres""",


"""All the news of our app""": u"""Al het nieuws over onze app""",


"""An unknown error has occurred""": u"""Er is een onbekende fout opgetreden""",


"""anonymous_user""": u"""Anonieme gebruiker""",


"""answer""": u"""Antwoord""",


"""App news""": u"""App nieuws""",


"""app""": u"""App""",


"""app_website_oca""": u"""http://onzestadapp.be""",


"""app_website_rogerthat""": u"""https://rogerth.at""",


"""around_you""": u"""Rondom u""",


"""association""": u"""Vereniging""",


"""Associations""": u"""Verenigingen""",


"""broadcast_reminder_explanation""": u"""U ontvangt deze notificatie omdat u bent ingeschreven op: %(broadcast_type)s""",


"""button""": u"""Knop""",


"""Can not connect to server""": u"""Kan geen connectie maken met de server""",


"""Cancel""": u"""Annuleren""",


"""cannot_register_app_disabled""": u"""Beste, u kunt niet meer registeren in de %(app)s app omdat deze niet langer beschikbaar is.""",


"""Care""": u"""Zorg""",


"""chat_error_delete_last_admin""": u"""De laatste beheerder van een chat kan niet worden verwijderd""",


"""City news""": u"""Stedelijk nieuws""",


"""click_here_to_reset_your_app_password""": u"""Click hier om uw %(app_name)s paswoord te resetten.""",


"""Community news""": u"""Gemeentelijk nieuws""",


"""Coronavirus info""": u"""Coronavirus info""",


"""The latest information about COVID-19""": u"""De meest recente informatie over COVID-19""",


"""Community Services""": u"""Gemeentediensten""",


"""community_service""": u"""Gemeentedienst""",


"""continue""": u"""Verder gaan""",


"""Could not determine file type for attachment %(url)s""": u"""Kan bestandstype niet bepalen voor bijlage %(url)s""",


"""Could not download attachment %(url)s""": u"""Kan bijlage niet downloaden %(url)s""",


"""Current polls""": u"""Lopende bevragingen""",


"""current-version""": u"""Huidige versie""",


"""date""": u"""Datum""",


"""Deactivate""": u"""Deactiveren""",


"""dear_name""": u"""Beste %(name)s""",


"""Decline invitation""": u"""Verzoek weigeren""",


"""Discover our new app""": u"""Ontdek onze app""",


"""Distance: %(distance)s km""": u"""Afstand: %(distance)s km""",


"""E-mail address""": u"""E-mailadres""",


"""eID data""": u"""eID data""",


"""Enter your reply:""": u"""Voer uw antwoord in:""",


"""Error""": u"""Fout""",


"""Events""": u"""Evenementen""",


"""Expected traffic""": u"""Verwachte verkeershinder""",


"""Failed to unregister""": u"""Uitschrijven mislukt""",


"""Failed to upload the photo to %(service_name)s""": u"""Fout tijdens het uploaden van de foto naar %(service_name)s""",


"""Flow result of %(user)s for %(flow)s""": u"""Flow resultaat van %(user)s voor %(flow)s """,


"""forms.click_button_to_test""": u"""Klik op de knop om uw bevraging uit te testen.""",


"""forms.click_to_test_your_form""": u"""Klik deze notificatie om uw bevraging te testen.""",


"""forms.max_submission_count_reached""": u"""Het formulier kon niet worden ingediend omdat u het al %(submission_count)s keer hebt ingediend""",


"""forms.test_form""": u"""Test bevraging""",


"""forms.test_form_x""": u"""Test bevraging: %(title)s""",


"""Group chat""": u"""Groepschat""",


"""http://www.ourcityapps.com""": u"""http://www.onzestadapp.be""",


"""i_agree_to_toc""": u"""Ik ga akkoord met de Algemene Voorwaarden""",


"""If you cannot access the link above, you can paste the following address into your browser:""": u"""Als bovenstaande link niet werkt kan u onderstaande URL kopiëren en plakken in uw browser.""",


"""Install %(other_app_name)s""": u"""Installeer %(other_app_name)s""",


"""Invalid download_url (%(url)s). It must be reachable over http or https.""": u"""Ongeldige hyperlink (%(url)s). De url moet bereikbaar zijn via http of https.""",


"""Invite %(name)s to connect on %(app_name)s""": u"""%(name)s uitnodigen op %(app_name)s""",


"""Invite %(name)s""": u"""%(name)s uitnodigen""",


"""Kind regards""": u"""Met vriendelijke groeten""",


"""Local""": u"""Lokaal""",


"""Location: %(address)s""": u"""Locatie: %(address)s.""",


"""log_out""": u"""Afmelden""",


"""mdp_missing_address""": u"""Het adres dat opgeslagen is in uw MYDIGIPASS account is onvolledig. Gelieve uw adres te configureren in MYDIGIPASS en opnieuw te proberen.""",


"""mdp_missing_eid_data""": u"""Er is geen eID data opgeslagen in uw MYDIGIPASS account. Gelieve uw eID te configureren in MYDIGIPASS en opnieuw te proberen.""",


"""mdp_missing_email""": u"""Er is geen e-mailadres opgeslagen in uw MYDIGIPASS account. Gelieve uw e-mailadres te configureren in MYDIGIPASS en opnieuw te proberen.""",


"""mdp_missing_phone""": u"""Er is geen telefoonnummer opgeslagen in uw MYDIGIPASS account. Gelieve uw telefoonnummer te configureren in MYDIGIPASS en opnieuw te proberen.""",


"""mdp_missing_profile""": u"""De personalia opgeslagen in uw MYDIGIPASS account zijn onvolledig. Gelieve uw profiel te vervolledigen in MYDIGIPASS en opnieuw te proberen.""",


"""mdp_missing_scopes""": u"""Er ontbreken gegevens in uw MYDIGIPASS account. De volgende gegevens ontbreken: %(missing_data)s

Vervolledig uw MYDIGIPASS account en probeer het opnieuw.

Zorg er ook voor dat u de laatste versie van de \"MYDIGIPASS Authenticator for Mobile\" app heeft.""",


"""merchant""": u"""Handelaar""",


"""Merchants""": u"""Handelaars""",


"""My services""": u"""Mijn diensten""",


"""Nearby services""": u"""Diensten in je buurt""",


"""New job match""": u"""Nieuwe vacature beschikbaar""",


"""New job matches""": u"""Nieuwe vacatures beschikbaar""",


"""new_news_available""": u"""Nieuw nieuws beschikbaar""",


"""new_news_available_for_group""": u"""Nieuw nieuws beschikbaar in %(group)s""",


"""News about events""": u"""Nieuws over activiteiten""",


"""News hasn't been setup yet for this app""": u"""De nieuwsstroom is nog niet ingesteld voor deze app""",


"""No events""": u"""Geen evenementen""",


"""No matching service found""": u"""Geen resultaten gevonden.""",


"""No news yet""": u"""Nog geen nieuws""",


"""No news""": u"""Geen nieuws""",


"""No polls""": u"""Geen bevragingen""",


"""No press""": u"""Geen pers""",


"""No promotions""": u"""Geen acties""",


"""No service found""": u"""Geen resultaten gevonden.""",


"""No traffic""": u"""Geen verkeersinfo""",


"""notify_service_location_tracking""": u"""%(service)s volgt uw locatie tot %(until)s.""",


"""OCA""": u"""Onze Stad App""",


"""open_link""": u"""%(link)s openen""",


"""password reset""": u"""Paswoord resetten.""",


"""payments.account_already_exists""": u"""Er bestaat al een account met deze valuta (%(currency)s). Kies een andere valuta of een ander portemonnee type.""",


"""payments.cannot_verify_wallet_type""": u"""Dit soort portemonnee kan niet worden gevalideerd.""",


"""payments.continue_adding_credit_card_info""": u"""Om door te gaan met het toevoegen van deze creditcard, moet u de creditcardgegevens op een externe website invoeren.""",


"""payments.currency_unknown""": u"""De valuta van deze portemonnee kon niet worden bepaald.""",


"""payments.duplicate_wallet""": u"""Er bestaat al een portefeuille met opgegeven gegevens.""",


"""payments.enter_code_present_in_transaction_on_bank_account""": u"""Voer de code in van transactie die is gemaakt op deze bankrekening.""",


"""payments.insufficient_funds""": u"""Deze portemonnee bevat niet genoeg geld om de transactie te plegen.""",


"""payments.invalid_iban""": u"""Ongeldig IBAN nummer, controleer of u het correct heeft ingevoerd.""",


"""payments.invalid_verification_code""": u"""Ongeldige verificatie code.""",


"""payments.permission_denied""": u"""U heeft geen permissie om deze actie te doen.""",


"""payments.provider_not_found""": u"""Betalingsaanbieder niet gevonden.""",


"""payments.ref""": u"""Ref.""",


"""payments.transaction_already_initiated""": u"""Deze transactie is al door een andere gebruiker gestart.""",


"""payments.transaction_finished""": u"""Deze transactie is al afgerond.""",


"""payments.transaction_not_found""": u"""Transactie niet gevonden.""",


"""payments.transaction_not_initiated""": u"""Deze transactie is nog niet gestart.""",


"""payments.unknown""": u"""Er is een onbekende fout opgetreden. Probeer het later nogmaals.""",


"""Phone number""": u"""Telefoonnummer""",


"""Please try again later.""": u"""Probeer het later opnieuw.""",


"""Please use this secure URL to reset your password within 5 days.""": u"""Gelieve deze beveiligde link te gebruiken om uw paswoord te resetten.""",


"""please_agree_to_toc""": u"""U moet akkoord gaan met de Algemene Voorwaarden voordat u kan verdergaan""",


"""please_review_updated_tac""": u"""Lees onze bijgewerkte Algemene voorwaarden voordat u verder gaat""",


"""Polls""": u"""Bevragingen""",


"""Press""": u"""Pers""",


"""privacy-policy""": u"""Privacybeleid""",


"""Profile""": u"""Profiel""",


"""Promotions in and around your city""": u"""Acties en promoties in uw stad""",


"""Promotions in and around your community""": u"""Acties en promoties in uw gemeente""",


"""Promotions""": u"""Promoties""",


"""read_the_toc_to_continue""": u"""Lees de algemene voorwaarden om verder te gaan""",


"""Received location of %(name)s.

Accuracy: %(accuracy)sm""": u"""Locatie van %(name)s gevonden.

Nauwkeurigheid: %(accuracy)sm""",


"""received_password_reset_request_for_app""": u"""We hebben uw aanvraag om uw paswoord van %(app_name)s te resetten goed ontvangen.""",


"""Regional""": u"""Regionaal""",


"""Reply""": u"""Antwoorden""",


"""rogerthat-payment.account""": u"""{{ provider }} Rekening""",


"""rogerthat-payment.bank""": u"""Bankrekening""",


"""rogerthat-payment.creditcard""": u"""Kredietkaart""",


"""Save""": u"""Bewaren""",


"""Scan QR code to discover!""": u"""Scan QR code om te ontdekken!""",


"""Search results""": u"""Zoekresultaten""",


"""Send reply""": u"""Zend antwoord""",


"""Service %(name)s wants to connect with you via %(app_name)s.""": u"""Dienst %(name)s wenst met u te communiceren via %(app_name)s.""",


"""service""": u"""Service""",


"""Services""": u"""Diensten""",


"""Show map""": u"""Toon kaart""",


"""signup""": u"""Registratie""",


"""Spaces are not allowed in an e-mail address""": u"""Spaties zijn niet toegestaan in een e-mail adres""",


"""Submit""": u"""Versturen""",


"""successfully_unsubscribed_broadcast_type""": u"""U bent met succes uitgeschreven op meldingen met type \"%(notification_type)s\" van %(service)s""",


"""tag""": u"""Label""",


"""terms-and-conditions""": u"""Algemene voorwaarden""",


"""terms-and-conditions-service""": u"""Algemene voorwaarden""",


"""thank_you_for_using_app""": u"""Bedankt om de %(app_name)s app te gebruiken!""",


"""The latest news of your city""": u"""De laatste nieuwtjes over uw stad""",


"""The latest news of your community""": u"""De laatste nieuwtjes over uw gemeente""",


"""The scanned QR code is not supported by the %(app_name)s app""": u"""De gescande QR-code wordt niet ondersteund door de %(app_name)s app""",


"""the_app_support_email_address_html""": u"""<a href=\"mailto:%(email)s\">%(app_name)s support</a>""",


"""the_app_team""": u"""Het %(app_name)s Team""",


"""the_our_city_app_coach_email_address""": u"""coach@onzestadapp.be""",


"""the_our_city_app_coach_email_address_html""": u"""de <a href=\"mailto:%(email)s\">Onze Stad Coach</a>""",


"""the_our_city_app_team""": u"""Het Onze Stad App Team""",


"""There are no events at this time""": u"""Er zijn op dit moment geen evenementen""",


"""There are no local press articles at this time""": u"""Er zijn op dit moment geen lokale krantenartikelen""",


"""There are no polls at this time""": u"""Er zijn geen bevragingen op dit moment""",


"""There are no promotions at this time""": u"""Er zijn op dit moment geen lopende acties""",


"""There is no e-mail address configured in your facebook account. Please use the e-mail based login.""": u"""Er is geen e-mailadres geconfigureerd in je Facebook account. Gelieve gebruik te maken van de e-mailgebaseerde login.""",


"""There is no news at this time""": u"""Er zijn geen nieuwsberichten op dit moment""",


"""There is no traffic at this time""": u"""Er is op dit moment geen verkeersinfo""",


"""This service is not supported by the %(current_app_name)s app. Please install the %(other_app_name)s app.""": u"""Deze service wordt niet ondersteund door de %(current_app_name)s app. Installeer de %(other_app_name)s app.""",


"""To reset your password, please enter your password twice on the page that opens.""": u"""Gelieve uw nieuw paswoord 2 maal in te geven om uw paswoord te resetten.""",


"""Traffic""": u"""Verkeer""",


"""Trafic""": u"""Verkeer""",


"""Unknown""": u"""Onbekend""",


"""Unsubscribe""": u"""Uitschrijven""",


"""User %(name)s has requested to share your location.""": u"""%(name)s heeft u een verzoek gestuurd om uw locatie te bepalen.""",


"""User %(name)s wants to get in touch with you via %(app_name)s.""": u"""%(name)s wenst met u te communiceren via %(app_name)s.""",


"""user""": u"""Gebruiker""",


"""user_data_download_duplicate""": u"""We hebben een link naar %(email)s gestuurd. De eenvoudigste manier om uw gegevens te downloaden is om uw e-mail op een computer te controleren.""",


"""user_data_download_ready_summary""": u"""Uw gegevensdownload is gereed""",


"""user_data_download_started""": u"""Zodra we uw bestand hebben gemaakt, sturen we u een e-mail om u te laten weten dat het compleet is en klaar om te worden gedownload.
Om veiligheidsredenen zal uw bestand slechts enkele dagen nadat u een e-mail van ons hebt ontvangen kunnen worden gedownload. Controleer daarom uw e-mail voor ons bericht.""",


"""We could not determine the location of %(name)s.""": u"""De locatie van %(name)s kon niet bepaald worden.""",


"""Which type of broadcasts do you wish to receive?""": u"""Welke types van notificaties wenst u te ontvangen?""",


"""Why do you wish to deactivate your account?""": u"""Waarom wenst u uw account te deactiveren?""",


"""Why do you wish to unsubscribe to this e-mail?""": u"""Waarom wenst u zich uit te schrijven voor deze e-mail?""",


"""You are already connected with %(name)s.""": u"""U bent reeds geconnecteerd met %(name)s.""",


"""You are now unsubscribed.""": u"""U bent nu uitgeschreven.""",


"""You can not register with this e-mail address""": u"""U kan zich niet registreren met dit e-mail adres""",


"""You have been logged out on your request""": u"""U bent uitgelogd op uw verzoek""",


"""Your account has been deleted on your request""": u"""Uw account werd op uw verzoek verwijderd""",


"""Your city in the press""": u"""Uw stad in de krant""",


"""Your community in the press""": u"""Uw gemeente in de krant""",


"""Your device was unregistered because the same account was used to register the following device '%(device_name)s'""": u"""U bent uitgelogd omdat u reeds ingelogd was op het volgende toestel: %(device_name)s""",


"""Your upload is completed""": u"""Uw upload is voltooid."""}


# ###########################################################################################


D["pt_BR"] = {


"""%(app_name)s has %(count)d new messages for you""": u"""%(app_name)s tem %(count)d novas mensagens para você""",


"""%(app_name)s has 1 new message for you""": u"""%(app_name)s tem 1 nova mensagem para você""",


"""%(app_name)s mobile registration""": u"""Registro do %(app_name)s para dispositivo móvel""",


"""%(name)s accepted your location sharing request.
Latest information:

Accuracy: %(accuracy)sm""": u"""%(name)s aceitou sua solicitação para compartilhar localização.
Informação mais recente:

Precisão: %(accuracy)sm""",


"""%(name)s accepted your location sharing request. Unfortunately we could not determine his/her location at this moment.""": u"""%(name)s aceitou sua solicitação para compartilhar localização. Infelizmente, não é possível determinar a localização dele(a) neste momento.""",


"""%(name)s added a personal note:
%(message)s""": u"""%(name)s acrescentou uma nota pessoal:
%(message)s""",


"""%(name)s declined your request to track his/her location.""": u"""%(name)s não aceitou sua solicitação para rastrear a localização dele(a).""",


"""%(name)s does not have a device which supports location tracking.""": u"""%(name)s não possui um dispositivo que seja compatível com o rastreamento da localização.""",


"""%(name)s invites you to the %(app_name)s app!""": u"""%(name)s convidou você para o aplicativo %(app_name)s!""",


"""%(name)s just joined %(app_name)s, and we found you in his facebook friends list!""": u"""%(name)s acaba de entrar no %(app_name)s, e encontramos você na sua lista de amigos do Facebook.""",


"""%(name_or_email)s added a personal note:

%(message)s""": u"""%(name_or_email)s acrescentou uma nota pessoal:

%(message)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.

About %(service_name)s:
%(service_description)s""": u"""%(user_name)s recomenda que você se conecte a %(service_name)s no %(app_name)s.

Sobre %(service_name)s:
%(service_description)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.""": u"""%(user_name)s recomenda que você se conecte a %(service_name)s no %(app_name)s.""",


"""_automatic_detection_invitation""": u"""Olá,

Acabamos de dar-lhe as boas-vindas à nossa empresa.
Você sabia que também oferecemos nossos serviços através do aplicativo %(app_name)s?
Clique no botão \"Adicionar a esta aplicación\" para adicionar-nos na sua lista de serviços.

Atenciosamente,
%(service_name)s.""",


"""_enable_location_services_ios7""": u"""Para ativar os serviços de localização:
1. Saia do aplicativo %(app_name)s e vá para Configurações.
2. Toque em Privacidade > Serviços de Localização.
3. Procure %(app_name)s e mude o botão para ON.""",


"""_enable_location_services_ios8""": u"""Para ativar os serviços de localização:
1. Saia do aplicativo %(app_name)s e vá para Configurações.
2. Toque em Privacidade > Serviços de Localização.
3. Procure %(app_name)s, toque em %(app_name)s e configure o acesso à localização como 'Sempre'.""",


"""_friend_denied_location_services""": u"""%(name)s desabilitou os serviços de localização para o aplicativo %(app_name)s""",


"""_friendship_accepted""": u"""Olá %(name)s,
%(friend_name)s é agora um contato seu.""",


"""_friendship_established""": u"""Olá %(name)s,
Agora você é amigo de %(friend_name)s.""",


"""_friendship_request_failed""": u"""Olá %(name)s,
Ocorreu uma falha na sua solicitação para conectar-se com %(friend_name)s.
Pressione o botão \"convidar\" para convidar %(friend_name)s.""",


"""_invited_too_often""": u"""Olá %(name)s,
Você convidou %(friend_email)s 3 vezes.
Para prevenir spam, %(app_name)s não enviará mais convites.""",


"""_invited_too_often_this_week""": u"""Olá %(name)s,
Você já tinha convidado %(friend_email)s nesta semana.
Para prevenir spam, %(app_name)s não enviará mais convites.""",


"""_invited_yourself""": u"""Olá %(name)s,
Você tentou iniciar amizade com você mesmo.
Infelizmente, isso não é possível.""",


"""_invitee_was_already_friend""": u"""Olá %(name)s,
Você tentou convidar %(friend_email)s que já está na sua lista de amigos.""",


"""_location_services_denied""": u"""%(name)s solicitou sua localização, mas você desabilitou os serviços de localização para o aplicativo %(app_name)s.""",


"""_unsupported_attachment_file_type""": u"""Formato de arquivo não compatível para o anexo %(url)s
Somente arquivos em formato pdf, jpeg e png são compatíveis.""",


"""A-Z""": u"""A-Z""",


"""About""": u"""Sobre""",


"""Accept invitation""": u"""Aceitar convite""",


"""Add to my services""": u"""Adicionar a esta aplicación""",


"""app_website_rogerthat""": u"""https://rogerth.at""",


"""Associations""": u"""Associações""",


"""Cancel""": u"""Cancelar""",


"""Care""": u"""Assistência """,


"""Community Services""": u"""Serviços para a comunidade""",


"""continue""": u"""Continuar""",


"""Could not determine file type for attachment %(url)s""": u"""Não foi possível determinar o formato de arquivo do anexo %(url)s""",


"""Could not download attachment %(url)s""": u"""Não foi possível fazer download do anexo %(url)s""",


"""Decline invitation""": u"""Recusar convite""",


"""Discover our new app""": u"""Encontrar nosso aplicativo""",


"""Distance: %(distance)s km""": u"""Distância: %(distance)s km""",


"""E-mail address""": u"""Endereço de e-mail""",


"""Enter your reply:""": u"""Inserir sua resposta:""",


"""Error""": u"""Erro""",


"""Failed to upload the photo to %(service_name)s""": u"""Falha ao fazer upload da foto para %(service_name)s""",


"""Flow result of %(user)s for %(flow)s""": u"""Resultado do fluxo de %(user)s para %(flow)s""",


"""Install %(other_app_name)s""": u"""Instalar %(other_app_name)s""",


"""Invalid download_url (%(url)s). It must be reachable over http or https.""": u"""Hyperlink (%(url)s) inválido. Deve ser acessível com http ou https.""",


"""Invite %(name)s to connect on %(app_name)s""": u"""Convidar %(name)s para se conectar a %(app_name)s""",


"""Invite %(name)s""": u"""Convidar %(name)s""",


"""Location: %(address)s""": u"""Localização: %(address)s.""",


"""Merchants""": u"""Comerciantes""",


"""My services""": u"""Meus serviços""",


"""Nearby services""": u"""Serviços próximos""",


"""No matching service found""": u"""Nenhum serviço correspondente encontrado.""",


"""No service found""": u"""Nenhum serviço encontrado.""",


"""notify_service_location_tracking""": u"""%(service)s está rastreando sua localização até %(until)s.""",


"""Phone number""": u"""Número de telefone""",


"""Please try again later.""": u"""Tente novamente mais tarde.""",


"""Received location of %(name)s.

Accuracy: %(accuracy)sm""": u"""Localização de %(name)s recebida.

Precisão: %(accuracy)sm""",


"""Reply""": u"""Resposta""",


"""Save""": u"""Salvar""",


"""Scan QR code to discover!""": u"""Escaneie o código QR para descobrir!""",


"""Search results""": u"""Resultados da pesquisa""",


"""Send reply""": u"""Enviar resposta""",


"""Service %(name)s wants to connect with you via %(app_name)s.""": u"""O serviço de %(name)s quer entrar em contato com você através do %(app_name)s.""",


"""Services""": u"""Serviços""",


"""Show map""": u"""Mostrar mapa""",


"""The scanned QR code is not supported by the %(app_name)s app""": u"""O código QR escaneado não é compatível com o aplicativo %(app_name)s """,


"""There is no e-mail address configured in your facebook account. Please use the e-mail based login.""": u"""Não há um endereço de e-mail configurado na sua conta do Facebook. Use o e-mail para fazer o login.""",


"""This service is not supported by the %(current_app_name)s app. Please install the %(other_app_name)s app.""": u"""Este serviço não é compatível com o aplicativo %(current_app_name)s. Instale o aplicativo %(other_app_name)s.""",


"""Unknown""": u"""Desconhecido""",


"""User %(name)s has requested to share your location.""": u"""O usuário %(name)s solicitou que você compartilhe sua localização.""",


"""User %(name)s wants to get in touch with you via %(app_name)s.""": u"""%(name)s deseja entrar em contato com você pelo  %(app_name)s.""",


"""We could not determine the location of %(name)s.""": u"""Não conseguimos determinar a localização de %(name)s.""",


"""Which type of broadcasts do you wish to receive?""": u"""Que tipo de programação deseja receber?""",


"""You are already connected with %(name)s.""": u"""Você já está conectado com %(name)s.""",


"""You can not register with this e-mail address""": u"""Você não pode se registrar com esse endereço de e-mail"""}


# ###########################################################################################

D["ro"] = {


"""%(app_name)s has %(count)d new messages for you""": u"""%(app_name)s are %(count)d mesaje noi pentru tine""",


"""%(app_name)s has 1 new message for you""": u"""%(app_name)s are 1 mesaj nou pentru tine""",


"""%(app_name)s mobile registration""": u"""Inregistrare mobila a %(app_name)s """,


"""%(name)s accepted your location sharing request.
Latest information:

Accuracy: %(accuracy)sm""": u"""%(name)s a acceptat cererea pentru determinarea locatiei.
Cele mai recente informatii:

Acuratete: %(accuracy)sm""",


"""%(name)s accepted your location sharing request. Unfortunately we could not determine his/her location at this moment.""": u"""%(name)s a acceptat cererea pentru determinarea locației. Din păcate, nu am putut stabili locația în acest moment.""",


"""%(name)s added a personal note:
%(message)s""": u"""%(name)s a adaugat un mesaj personal:
%(message)s""",


"""%(name)s declined your request to track his/her location.""": u"""%(name)s a refuzat cererea de fi localizati.""",


"""%(name)s does not have a device which supports location tracking.""": u"""%(name)s nu detin un dispozitiv care permite localizarea.""",


"""%(name)s invites you to the %(app_name)s app!""": u"""%(name)s te invita in aplicatia  %(app_name)s !""",


"""%(name)s just joined %(app_name)s, and we found you in his facebook friends list!""": u"""%(name)s tocmai s-a alaturat %(app_name)s, si v-am gasit in lista lui de prieteni de pe Facebook.""",


"""%(name_or_email)s added a personal note:

%(message)s""": u"""%(name_or_email)s a adaugat un mesaj personal:

%(message)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.

About %(service_name)s:
%(service_description)s""": u"""%(user_name)s vă recomandă să vă conectați la %(service_name)s in %(app_name)s.

Despre %(service_name)s:
%(service_description)s""",


"""%(user_name)s recommends you to connect to %(service_name)s on %(app_name)s.""": u"""%(user_name)s vă recomandă să vă conectați la %(service_name)s in %(app_name)s.""",


"""_automatic_detection_invitation""": u"""Buna ziua,
Bine ati venit la firma noastra.
Stiati ca va putem oferii, de asemenea, serviciile noastre prin intermediul aplicatiei %(app_name)s ?
Dati clic pe butonul \"Adauga la această aplicație\" pentru a ne adauga in lista dvs. de servicii.
Cu stima, %(service_name)s.""",


"""_enable_location_services_ios7""": u"""Pentru a activa serviciile de localizare:
1. Parasiti aplicatia %(app_name)s si accesati aplicatia Configurări.
2. Tap Intimitate  > Servicii de localizare
3. Cauta %(app_name)s si schimba comutatorul pe ON""",


"""_enable_location_services_ios8""": u"""Pentru a activa serviciile de localizare:
1. Parasiti aplicatia %(app_name)s si accesati aplicatia Configurări.
2. Tap Intimitate  > Servicii de localizare
3. Cauta %(app_name)s si schimba accesarea localizării la 'Întotdeauna'""",


"""_friend_denied_location_services""": u"""%(name)s a dezactivat serviciile de localizare pentru aplicația %(app_name)s""",


"""_friendship_accepted""": u"""Buna %(name)s,
%(friend_name)s este acum conectat la tine.""",


"""_friendship_established""": u"""Buna %(name)s,
Ati devenit prieten cu %(friend_name)s.""",


"""_friendship_request_failed""": u"""Buna %(name)s,
Cererea de conexiune cu %(friend_name)s a esuat.
Apasati butonul de invita pentru a-l invita pe %(friend_name)s.""",


"""_invited_too_often""": u"""Buna %(name)s,
L-ati invitat pe %(friend_email)s de 3 ori.
Pentru a prevenii spam-ul, %(app_name)s nu va mai trimite nici o invitatie.""",


"""_invited_too_often_this_week""": u"""Buna %(name)s,
Deja l-ati invitat pe %(friend_email)s in aceasta saptamana.
Pentru a prevenii spam-ul, %(app_name)s nu va mai trimite nici o invitatie.""",


"""_invited_yourself""": u"""Buna %(name)s,
Ati incercat sa devii prieten cu tine insuti, din pacate acest lucru nu este posibil.""",


"""_invitee_was_already_friend""": u"""Buna %(name)s,
Ati incercat sa il invitati pe %(friend_email)s care este deja in lista dvs. de prieteni.""",


"""_location_services_denied""": u"""%(name)s a solicitat locația dvs. dar serviciile de localizare sunt dezactivate pentru aplicația %(app_name)s.""",


"""_unsupported_attachment_file_type""": u"""Tip de fişier neacceptat pentru ataşarea %(url)s
Suntem acceptă numai fişiere pdf, jpeg şi png""",


"""About""": u"""Despre""",


"""Accept invitation""": u"""Accepta invitatia""",


"""account_already_deactivated""": u"""Nu sunteți abonat (mai) la aplicația %(app_name)s cu acest cont (%(account)s).""",


"""account_already_disconnected_from_service""": u"""Nu sunteți abonat (mai) la %(service_name)s.""",


"""Add to my services""": u"""Adauga la această aplicație""",


"""Address""": u"""Adresa""",


"""An unknown error has occurred""": u"""A aparut o eroare necunoscuta""",


"""app""": u"""App""",


"""app_website_rogerthat""": u"""https://rogerth.at""",


"""association""": u"""Asociere""",


"""Associations""": u"""Asociatii""",


"""broadcast_reminder_explanation""": u"""Ați primit această notificare deoarece sunteți abonat la: %(broadcast_type)s""",


"""Can not connect to server""": u"""Nu se poate conecta la server""",


"""Cancel""": u"""Anuleaza""",


"""Care""": u"""Ingrijire""",


"""Community Services""": u"""Servicii comunitare""",


"""continue""": u"""Continua""",


"""Could not determine file type for attachment %(url)s""": u"""Nu a putut determina tipul de fișier pentru atașare %(url)s""",


"""Could not download attachment %(url)s""": u"""Nu poate descărca ataşament %(url)s""",


"""date""": u"""Data""",


"""dear_name""": u"""draga %(name)s""",


"""Decline invitation""": u"""Invitatie refuzata""",


"""Discover our new app""": u"""Descopera noua noastra aplicatie""",


"""Distance: %(distance)s km""": u"""Distanta: %(distance)s km""",


"""E-mail address""": u"""Adresa de e-mail""",


"""eID data""": u"""date eID""",


"""Enter your reply:""": u"""Introduceti raspunsul dvs:""",


"""Error""": u"""Eroare""",


"""Events""": u"""Evenimente""",


"""Failed to unregister""": u"""Nu a reusit sa se retraga""",


"""Failed to upload the photo to %(service_name)s""": u"""Eroare la incarcarea pozei in %(service_name)s""",


"""Flow result of %(user)s for %(flow)s""": u"""Rezultatul flow-ului de %(user)s pentru %(flow)s""",


"""http://www.ourcityapps.com""": u"""http://www.ourcityapps.com""",


"""Install %(other_app_name)s""": u"""Instaleaza %(other_app_name)s""",


"""Invalid download_url (%(url)s). It must be reachable over http or https.""": u"""Hyperlink invalid (%(url)s). Acesta trebuie să fie accesibil pe http sau https.""",


"""Invite %(name)s to connect on %(app_name)s""": u"""Invita %(name)s pentru a se conecta la %(app_name)s""",


"""Invite %(name)s""": u"""Invita pe %(name)s""",


"""Kind regards""": u"""Salutări calde""",


"""Location: %(address)s""": u"""Locatia: %(address)s.""",


"""log_out""": u"""Delogare""",


"""mdp_missing_address""": u"""Adresa stocate în contul dvs. MIDIGIPASS este incomplet. Vă rugăm să configurați adresa în MYDIGIPASS și încercați din nou.""",


"""mdp_missing_eid_data""": u"""Nu există date de eID stocate în contul dvs. MIDIGIPASS. Vă rugăm să configurați datele eID în MYDIGIPASS și încercați din nou.""",


"""mdp_missing_email""": u"""Nu există nici o adresă de e-mail stocate în contul dvs. MIDIGIPASS. Vă rugăm să configurați adresa de e-mail în MYDIGIPASS și încercați din nou.""",


"""mdp_missing_phone""": u"""Nu există nici un număr de telefon stocat în contul dvs. MIDIGIPASS. Vă rugăm să configurați numărul de telefon în MYDIGIPASS și încercați din nou.""",


"""mdp_missing_profile""": u"""Informațiile cu caracter personal stocate în contul dvs. MIDIGIPASS este incomplet. Vă rugăm să completați profilul în MYDIGIPASS și încercați din nou.""",


"""mdp_missing_scopes""": u"""Nu există suficiente date disponibile în contul dvs. MYDIGIPASS. Următoarele date lipsesc: %(missing_data)s Vă rugăm să completați datele contului MYDIGIPASS și încercați din nou. De asemenea, asigurați-vă că aveți cea mai recentă versiune a \"MYDIGIPASS Authenticator pentru Mobile\" app.""",


"""Merchants""": u"""Comercianti""",


"""My services""": u"""Serviciile mele""",


"""Nearby services""": u"""Servicii din apropiere""",


"""No matching service found""": u"""Nu s-a gasit nici un serviciu care sa se potriveasca.""",


"""No service found""": u"""Nu există rezultate""",


"""notify_service_location_tracking""": u"""%(service)s urmărește locația dvs. până %(until)s.""",


"""OCA""": u"""Oraș App nostru""",


"""Phone number""": u"""Numar de telefon""",


"""Please try again later.""": u"""Va rugam sa incercati din nou mai tarziu.""",


"""Profile""": u"""Profil""",


"""Received location of %(name)s.

Accuracy: %(accuracy)sm""": u"""Locatia primita a %(name)s.

Acuratete: %(accuracy)sm""",


"""Reply""": u"""Raspuns""",


"""rogerthat-payment.creditcard""": u"""Card de credit""",


"""Save""": u"""Salveaza""",


"""Scan QR code to discover!""": u"""Scanati codul QR pentru a descoperi!""",


"""Search results""": u"""Rezultatele cautarii""",


"""Send reply""": u"""Trimite un raspuns""",


"""Service %(name)s wants to connect with you via %(app_name)s.""": u"""Serviciul %(name)s vrea sa se conecteze la tine prin %(app_name)s.""",


"""Services""": u"""Servicii""",


"""Show map""": u"""Arata harta""",


"""Spaces are not allowed in an e-mail address""": u"""Spațiile nu sunt permise într-o adresă de e-mail""",


"""Submit""": u"""Trimite""",


"""successfully_unsubscribed_broadcast_type""": u"""Ați fost dezabonat cu succes de la notificările cu tipul de \"%(notification_type)s\" de %(service)s.""",


"""The scanned QR code is not supported by the %(app_name)s app""": u"""Codul QR scanat nu este suportat de %(app_name)s app""",


"""the_app_support_email_address_html""": u"""<a href=\"mailto:%(email)s\">sprijin %(app_name)s</a>""",


"""the_app_team""": u"""Echipa %(app_name)s""",


"""the_our_city_app_coach_email_address""": u"""coach@ourcityapps.com""",


"""the_our_city_app_team""": u"""Echipa de Orasul nostru App""",


"""There is no e-mail address configured in your facebook account. Please use the e-mail based login.""": u"""Nu există nici o adresă de e-mail configurată în contul dvs. de Facebook. Va rugam sa folositi metoda de conectare prin e-mail.""",


"""This service is not supported by the %(current_app_name)s app. Please install the %(other_app_name)s app.""": u"""Acest serviciu nu este suportat de aplicatia %(current_app_name)s app. Va rugam instalati aplicatia %(other_app_name)s.""",


"""Unknown""": u"""Necunoscut""",


"""Unsubscribe""": u"""dezabonare de""",


"""User %(name)s has requested to share your location.""": u"""Utilizatorul %(name)s a solicitat dezvaluirea locatiei dumneavoastra.""",


"""User %(name)s wants to get in touch with you via %(app_name)s.""": u"""%(name)s vrea sa intre in contact cu tine prin %(app_name)s.""",


"""user""": u"""Utilizator""",


"""We could not determine the location of %(name)s.""": u"""Nu am putut identifica locatia %(name)s.""",


"""Which type of broadcasts do you wish to receive?""": u"""Ce tip de notificari doriti sa primiti?""",


"""Why do you wish to unsubscribe to this e-mail?""": u"""De ce va doriti sa va dezabonati la acest e-mail?""",


"""You are already connected with %(name)s.""": u"""Sunteti deja conectat cu %(name)s.""",


"""You are now unsubscribed.""": u"""Sunteți acum dezabonat.""",


"""You can not register with this e-mail address""": u"""Nu va puteți înregistra cu această adresă de e-mail"""}



# Keep this line at the bottom
SUPPORTED_LANGUAGES = D.keys()
